import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

/**
 * `docs.roocode.com` **301**s to the GitHub Pages site. The redirect target is recorded
 * because the URL a reviewer follows is part of the claim — the second adapter in this
 * roster whose documented URL has moved (Windsurf's was the first).
 */
const RULES_DOCS: SourceLink = {
  url: 'https://roocodeinc.github.io/Roo-Code/features/custom-instructions',
  title: 'Roo Code — Custom Instructions',
  retrieved: '2026-09-04',
};

const MCP_DOCS: SourceLink = {
  url: 'https://roocodeinc.github.io/Roo-Code/features/mcp/using-mcp-in-roo',
  title: 'Roo Code — Using MCP in Roo',
  retrieved: '2026-09-04',
};

/**
 * What Roo Code actually loads.
 *
 * **Everything applicable is aggregated**, not just the nearest match: the vendor is
 * explicit that rules load from *all* applicable directories rather than the first one with
 * files. Ordering here therefore ranks specificity, not authority.
 *
 * The one real ranking is the fallback rule: `.roorules` and `.clinerules` are read **only
 * when the corresponding directories are absent or empty**.
 */
export const docs: AdapterDocs = {
  toolName: 'Roo Code',
  homepage: 'https://roocode.com',
  verifiedAgainst: { version: 'Roo Code docs as published 2026-09-04', date: '2026-09-04' },
  resolution: 'additive',
  files: [
    {
      pattern: '.roo/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      nesting: 'all-merged',
      description:
        'Workspace rules. Read recursively, including subdirectories, and concatenated sorted by basename only, case-insensitive. Rulegate prefixes each generated filename with a zero-padded index so that sort reproduces the canonical order.',
      source: RULES_DOCS,
    },
    {
      pattern: '.roo/rules-*/',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Mode-specific workspace rules, inserted before the generic ones. Rulegate has no canonical model for modes, so it never writes these; a repository that uses them keeps them untouched.',
      source: RULES_DOCS,
    },
    {
      pattern: '.roorules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Legacy single-file fallback, read only when .roo/rules/ is absent or empty. Rulegate imports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '.clinerules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Read for Cline compatibility, and only when the Roo directories are absent or empty. Managed by the cline adapter, not this one.',
      source: RULES_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Read from the workspace root by default, disabled by the roo-cline.useAgentRules setting. Generated by the codex adapter, so enabling roo-code and codex together sends Roo the same rules twice — `rulegate doctor` reports the duplicate and its token cost.',
      source: RULES_DOCS,
    },
    {
      pattern: '.roo/mcp.json',
      scope: 'project',
      role: 'mcp',
      managed: true,
      description:
        'Project MCP servers. Takes precedence over the global configuration when a server name appears in both. Roo spells streamable HTTP "streamable-http" rather than "http".',
      source: MCP_DOCS,
    },
    {
      pattern: '~/.roo/rules/',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules, aggregated with the workspace ones rather than replaced by them. Outside the repository, so Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
  ],
  limits: { note: 'Roo Code publishes no size cap for rule files.' },
  notes: [
    {
      level: 'warn',
      message:
        'Roo Code sorts rule files by basename only, case-insensitively, and that ordering knows nothing about Rulegate’s `order` field. Generated filenames therefore carry a zero-padded index; renaming or reordering rules renames files, which is the cost of making Roo’s sort agree with the canonical one.',
      source: RULES_DOCS,
    },
    {
      level: 'warn',
      message:
        'Roo documents no variable substitution in .roo/mcp.json, so a canonical env: reference is written through as the literal text `env:NAME`. That is inert rather than wrong — Rulegate will not write a literal credential into a git-committed file under any flag — but the server will not authenticate until the value is supplied another way.',
      source: MCP_DOCS,
    },
    {
      level: 'info',
      message:
        'Roo reads every file in .roo/rules/ regardless of extension. Rulegate imports .md and .txt only; a rule kept under another extension is not lost from disk, but it will not be imported into .rulegate/.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        "Rulegate renders no agents for Roo Code. Roo's custom modes are a different concept — one `.roomodes` file of modes with `roleDefinition` and permission `groups`, which replace the assistant rather than hand work to it.",
      source: {
        url: 'https://roocodeinc.github.io/Roo-Code/features/custom-modes',
        title: 'Roo Code — Customizing Modes',
        retrieved: '2026-09-29',
      },
    },
  ],
  // Roo Code also reads mode-specific `skills-<mode>/` directories, which Rulegate does not generate.
  skills: {
    dirs: ['.roo/skills', '.agents/skills'],
    extensions: [],
    source: {
      url: 'https://roocodeinc.github.io/Roo-Code/features/skills',
      title: 'Roo Code — Skills',
      retrieved: '2026-09-29',
    },
  },
  // `argument-hint` is shown to the user only; no placeholder is documented, so a command using one is not rendered here.
  commands: {
    dir: '.roo/commands',
    extension: '.md',
    format: 'markdown',
    extensions: ['argument-hint', 'mode'],
    source: {
      url: 'https://roocodeinc.github.io/Roo-Code/features/slash-commands',
      title: 'Roo Code — Slash Commands',
      retrieved: '2026-09-29',
    },
  },
};
