import type { JsonValue } from '../model/ids.js';

export const MARKER_TEXT = 'generated by rulegate; edit .rulegate/ instead';
export const HTML_MARKER = `<!-- ${MARKER_TEXT} -->`;
export const HASH_MARKER = `# ${MARKER_TEXT}`;

/**
 * The marker is how a human — and `check` — can tell a generated file from a
 * hand-written one at a glance. It goes first wherever the format allows a leading
 * comment; formats that demand other content first (Cursor's `.mdc`, whose frontmatter
 * must be the first bytes) place it immediately after that content instead.
 */
export function withHtmlMarker(body: string, enabled = true): string {
  return enabled ? `${HTML_MARKER}\n\n${body}` : body;
}

export function withHashMarker(body: string, enabled = true): string {
  return enabled ? `${HASH_MARKER}\n\n${body}` : body;
}

/**
 * The key a generated JSON file carries its marker under (T035/T037).
 *
 * JSON has no comments, and MCP artifacts are JSON — so without this, `kind: 'mcp'`
 * output would be the one generated shape with no marker in it, and every place that
 * infers "we wrote this" from the marker (`hasMarker`, `doctor`, import's split-only-what
 * -you-wrote rule) would need a per-kind exception. `"//"` is the established
 * JSON-comment idiom, every consumer ignores keys it does not know, and it sorts ahead of
 * every ordinary key under `compareCodepoint`, so `stableJsonStringify` needs no special
 * case to keep it first.
 */
export const JSON_MARKER_KEY = '//';

/**
 * Add the marker to an object about to be serialized as JSON.
 *
 * Takes and returns the *value*, not rendered text: inserting a line into finished JSON
 * would mean parsing it back or splicing strings, and the second is how a generator
 * produces output that is not valid JSON.
 */
export function withJsonMarker(
  value: Record<string, JsonValue>,
  enabled = true,
): Record<string, JsonValue> {
  return enabled ? { [JSON_MARKER_KEY]: MARKER_TEXT, ...value } : value;
}

/** True when a file's opening bytes claim Rulegate generated it. */
export function hasMarker(contents: string): boolean {
  return contents.slice(0, 512).includes(MARKER_TEXT);
}
