import { describe, expect, it } from 'vitest';
import type { Canonical, McpServer } from '@rulegate/adapter-kit';
import { copilot, MCP_FILE } from '../src/index.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';

const FIXTURE = 'copilot-mcp';

async function render(mutate: (c: Canonical) => Canonical = (c) => c): Promise<string | undefined> {
  const ctx = await contextFor(`${FIXTURE}/input`, copilot);
  const artifacts = await copilot.write({ ...ctx, canonical: mutate(ctx.canonical) });
  return artifacts.find((a) => a.path === MCP_FILE)?.contents;
}

describe('copilot MCP output (T040)', () => {
  it('matches the hand-written golden byte for byte', async () => {
    await expectFixtureMatch(FIXTURE, copilot);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent(FIXTURE, copilot);
  });

  it('generates MCP for a repository with servers and no rules', async () => {
    // The regression guard for the demoted `rules.length === 0` early return. Before
    // T040 this adapter returned `[]` for the whole fixture.
    const actual = await renderFixture(FIXTURE, copilot);
    expect([...actual.keys()]).toEqual([MCP_FILE]);
  });

  it('renders the artifact as kind `mcp` with no provenance', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, copilot);
    const artifact = (await copilot.write(ctx)).find((a) => a.path === MCP_FILE);

    expect(artifact?.kind).toBe('mcp');
    expect(artifact?.provenance).toBeUndefined();
  });

  it('skips a server scoped to another tool, a disabled one and a global one', async () => {
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('cursor-only');
    expect(contents).not.toContain('disabled-server');
    expect(contents).not.toContain('user-global');
  });

  it('writes the servers under `servers`, not `mcpServers`', async () => {
    // The divergence that decides whether the file does anything at all. A `.mcp.json`
    // copied here parses cleanly and supplies no servers, so this is asserted both ways.
    const contents = (await render()) ?? '';
    const parsed = JSON.parse(contents) as Record<string, unknown>;
    expect(Object.keys(parsed)).toContain('servers');
    expect(Object.keys(parsed)).not.toContain('mcpServers');
  });

  it('spells an env reference the way VS Code expands it', async () => {
    const contents = (await render()) ?? '';
    expect(contents).toContain('"GITHUB_TOKEN": "${env:GITHUB_TOKEN}"');
    // Not Claude Code's spelling, and never the canonical one — no tool expands `env:`.
    expect(contents).not.toContain('"${GITHUB_TOKEN}"');
    expect(contents).not.toContain('"env:');
  });

  it('writes `type` on every server, stdio included', async () => {
    // Claude Code omits `type` on a stdio server and Cursor has no `type` key at all.
    // VS Code documents it for all three shapes, so this adapter cannot copy either.
    const servers = (JSON.parse((await render()) ?? '') as { servers: Record<string, object> })
      .servers;
    expect((servers['zebra-stdio'] as { type?: string }).type).toBe('stdio');
    expect((servers['alpha-http'] as { type?: string }).type).toBe('http');
  });

  it('keeps the sse distinction Cursor loses', async () => {
    const servers = (JSON.parse((await render()) ?? '') as { servers: Record<string, object> })
      .servers;
    expect((servers['linear-sse'] as { type?: string }).type).toBe('sse');
  });

  it('re-emits keys Rulegate does not interpret', async () => {
    expect((await render()) ?? '').toContain('"timeout": 600000');
  });

  it('is valid JSON whose marker key sorts first', async () => {
    const contents = (await render()) ?? '';
    expect(Object.keys(JSON.parse(contents) as object)[0]).toBe('//');
  });

  it('omits the marker when the manifest disables it', async () => {
    const contents =
      (await render((c) => ({
        ...c,
        manifest: { ...c.manifest, options: { ...c.manifest.options, marker: false } },
      }))) ?? '';
    expect(contents).not.toContain('generated by rulegate');
    expect(contents.startsWith('{\n  "servers"')).toBe(true);
  });

  it('renders nothing when no server targets this tool', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, copilot);
    expect(
      await copilot.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: [] } }),
    ).toEqual([]);
  });

  it('renders one order whatever order the servers arrive in', async () => {
    // Deliberately not a test of `selectMcpServers`' sort — `stableJsonStringify` sorts
    // deeply, so that sort is invisible to any JSON golden. What this pins is that the
    // bytes `state.json` hashes do not depend on input order. The sort's real guard is
    // `core/test/mcp.test.ts` and, as of T040, the codex TOML golden.
    const ctx = await contextFor(`${FIXTURE}/input`, copilot);
    const reversed: readonly McpServer[] = [...ctx.canonical.mcpServers].reverse();
    const rendered = async (servers: readonly McpServer[]) =>
      (await copilot.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: servers } })).find(
        (a) => a.path === MCP_FILE,
      )?.contents;

    expect(await rendered(reversed)).toBe(await rendered(ctx.canonical.mcpServers));
  });

  it('still refuses to write over a canonical source', async () => {
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: [MCP_FILE] },
    }));
    expect(contents).toBeUndefined();
  });
});
