import { describe, expect, it } from 'vitest';
import type { Canonical, McpServer } from '@rulegate/adapter-kit';
import { cursor, MCP_FILE } from '../src/index.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';

const FIXTURE = 'cursor-mcp';

async function render(mutate: (c: Canonical) => Canonical = (c) => c): Promise<string | undefined> {
  const ctx = await contextFor(`${FIXTURE}/input`, cursor);
  const artifacts = await cursor.write({ ...ctx, canonical: mutate(ctx.canonical) });
  return artifacts.find((a) => a.path === MCP_FILE)?.contents;
}

describe('cursor MCP output (T039)', () => {
  it('matches the hand-written golden byte for byte', async () => {
    await expectFixtureMatch(FIXTURE, cursor);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent(FIXTURE, cursor);
  });

  it('generates MCP for a repository with servers and no rules', async () => {
    const actual = await renderFixture(FIXTURE, cursor);
    expect([...actual.keys()]).toEqual([MCP_FILE]);
  });

  it('renders the artifact as kind `mcp` with no provenance', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, cursor);
    const artifact = (await cursor.write(ctx)).find((a) => a.path === MCP_FILE);

    expect(artifact?.kind).toBe('mcp');
    expect(artifact?.provenance).toBeUndefined();
  });

  it('includes a server scoped to this tool and skips disabled and global ones', async () => {
    const contents = (await render()) ?? '';
    expect(contents).toContain('cursor-only');
    expect(contents).not.toContain('disabled-server');
    expect(contents).not.toContain('user-global');
  });

  it('spells an env reference the way Cursor expands it', async () => {
    const contents = (await render()) ?? '';
    // One character apart from Claude Code's `${NAME}`, and the difference decides
    // whether the server receives a credential or the unexpanded text.
    expect(contents).toContain('"GITHUB_TOKEN": "${env:GITHUB_TOKEN}"');
    expect(contents).not.toContain('"${GITHUB_TOKEN}"');
  });

  it('writes no `type` key, because Cursor documents none', async () => {
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('"type"');
    // The documented loss: sse and http render identically here. Recorded in `docs.notes`
    // rather than left for a user to discover.
    const servers = (JSON.parse(contents) as { mcpServers: Record<string, object> }).mcpServers;
    expect(Object.keys(servers['linear-sse'] ?? {})).toEqual(['headers', 'url']);
    // An sse server and an http one differ only in their url. Asserted so that a future
    // `type` key added here has to change this test deliberately rather than by accident.
    expect(Object.keys(servers['linear-sse'] ?? {})).toEqual(
      Object.keys(servers['alpha-http'] ?? {}).filter((k) => k !== 'timeout'),
    );
  });

  it('re-emits keys Rulegate does not interpret', async () => {
    expect((await render()) ?? '').toContain('"timeout": 600000');
  });

  it('is valid JSON whose marker key sorts first', async () => {
    const contents = (await render()) ?? '';
    expect(Object.keys(JSON.parse(contents) as object)[0]).toBe('//');
  });

  it('omits the marker when the manifest disables it', async () => {
    const contents =
      (await render((c) => ({
        ...c,
        manifest: { ...c.manifest, options: { ...c.manifest.options, marker: false } },
      }))) ?? '';
    expect(contents).not.toContain('generated by rulegate');
  });

  it('renders nothing when no server targets this tool', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, cursor);
    expect(await cursor.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: [] } })).toEqual(
      [],
    );
  });

  it('renders one order whatever order the servers arrive in', async () => {
    // Deliberately NOT a test of `selectMcpServers`' sort: `stableJsonStringify` sorts every
    // key deeply, so an assertion on the id order here passes with that sort deleted —
    // verified by mutation. What this pins is the property that actually matters at this
    // level: the *bytes* do not depend on the order the servers were handed over, which is
    // what `state.json` hashes. The sort has its own guard in `core/test/mcp.test.ts`.
    const ctx = await contextFor(`${FIXTURE}/input`, cursor);
    const reversed: readonly McpServer[] = [...ctx.canonical.mcpServers].reverse();
    const rendered = async (servers: readonly McpServer[]) =>
      (await cursor.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: servers } })).find(
        (a) => a.path === MCP_FILE,
      )?.contents;

    expect(await rendered(reversed)).toBe(await rendered(ctx.canonical.mcpServers));
  });

  it('writes no empty .cursorrules when there are servers but no rules', async () => {
    // `rules.length === 0` used to return early for the whole adapter; moving it means the
    // legacy branch needs its own guard or it renders a file with nothing in it.
    const ctx = await contextFor(`${FIXTURE}/input`, cursor);
    const artifacts = await cursor.write({ ...ctx, options: { legacy: true } });
    expect(artifacts.map((a) => a.path)).toEqual([MCP_FILE]);
  });

  it('still refuses to write over a canonical source', async () => {
    // The mutation that removes this guard from both writers failed only the claude-code
    // test until this existed — the cursor half was a guard no test supplied an input for.
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: [MCP_FILE] },
    }));
    expect(contents).toBeUndefined();
  });
});
