/**
 * Every field of the canonical format that RFC-0001 is required to document.
 *
 * This list is the machine-checkable half of T003's validation ("the RFC covers every
 * field in the model with no undocumented type"). Adding a field to the model and
 * forgetting the RFC is the normal way a spec rots; here it fails a test instead.
 *
 * Add a field to the model -> add it here -> document it in the RFC.
 */
export const MODEL_FIELDS: readonly string[] = [
  // Manifest
  'schemaVersion',
  'tools',
  'enabled',
  'options',
  'marker',
  'backup',
  'canonicalSources',
  // Rule frontmatter
  'description',
  'globs',
  'order',
  // MCP servers (T035, RFC §11)
  'servers',
  'command',
  'args',
  'transport',
  'headers',
  'scope',
  // State
  'artifacts',
  'path',
  'hash',
  'adapter',
];

/** Format-level guarantees the RFC must state, not just imply. */
export const NORMATIVE_TOPICS: readonly string[] = [
  'NFC',
  'E_RULE_ID_CONFLICT',
  'E_NO_CANONICAL_SOURCE',
  'E_ARTIFACT_OVERWRITES_SOURCE',
  'generated by rulegate; edit .rulegate/ instead',
  'bare-agents-md',
  'env:GITHUB_TOKEN',
  'E_LITERAL_SECRET',
  '.rulegate/mcp/servers.yaml',
  'docs/determinism.md',
];
