import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { runAudit } from '../src/lib/audit.js';
import { sandbox, type Sandbox } from './helpers.js';

let sb: Sandbox;
beforeEach(async () => {
  sb = await sandbox();
});
afterEach(async () => {
  await sb.dispose();
});

const audit = async (): Promise<string> =>
  (
    await runAudit({ root: sb.root, claudeDir: sb.claudeDir, today: '2026-09-26', expect: '0.3.0' })
  ).join('\n');

describe('runAudit (T106)', () => {
  it('says TOO-EARLY on an empty project, and reads no clock of its own', async () => {
    const text = await audit();
    expect(text).toContain('2026-09-26');
    expect(text).toContain('MODE  TOO-EARLY');
    expect(text).toContain('SETUP  FRESH');
    expect(text).toContain('npx rulegate init');
  });

  it('never calls a store Rulegate generated legacy — state.json decides', async () => {
    await sb.put('.rulegate/rulegate.yaml', 'schemaVersion: 1\n');
    await sb.put('.cursor/rules/a.mdc', 'x');
    await sb.put('.clinerules', 'hand-written');
    await sb.put('.rulegate/state.json', {
      schemaVersion: 1,
      artifacts: [{ path: '.cursor/rules/a.mdc', hash: 'h' }],
    });
    const text = await audit();
    expect(text).toMatch(
      /\.cursor\/rules\/ +1 file\(s\) +1 B +— generated by rulegate, not legacy/,
    );
    expect(text).toContain('FOUND .clinerules');
    expect(text).toContain('preserve its content in .rulegate/rules/');
  });

  it('hands drift to rulegate check rather than checking it here', async () => {
    await sb.put('.rulegate/rulegate.yaml', 'schemaVersion: 1\n');
    expect(await audit()).toContain('drift: run `npx --no rulegate check`');
  });

  it('says a generated CLAUDE.md is trimmed in .rulegate/rules/, not in the file', async () => {
    await sb.put('CLAUDE.md', 'x\n'.repeat(250));
    await sb.put('.rulegate/state.json', {
      schemaVersion: 1,
      artifacts: [{ path: 'CLAUDE.md', hash: 'h' }],
    });
    expect(await audit()).toContain('It is generated — trim or narrow rules in .rulegate/rules/');
  });

  it('fails an agent-os plugin still enabled, and names its memory for migration', async () => {
    await sb.putHome('settings.json', { enabledPlugins: { 'agent-os@sayan-plugins': true } });
    await sb.put('.claude/agent-memory/agent-os-feature-cartographer/MEMORY.md', '');
    const text = await audit();
    expect(text).toContain('FAIL  agent-os@sayan-plugins is still enabled');
    expect(text).toContain('moves it to rulegate-feature-cartographer');
  });

  it('fails a hook whose target is missing', async () => {
    await sb.put('.claude/settings.json', {
      hooks: {
        SessionStart: [
          { hooks: [{ type: 'command', command: '"$CLAUDE_PROJECT_DIR/.claude/hooks/gone.sh"' }] },
        ],
      },
    });
    expect(await audit()).toContain('FAIL  SessionStart hook points at .claude/hooks/gone.sh');
  });
});
