import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync } from 'node:fs';
import { mkdir, symlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { guard, reminder } from '../src/lib/guard.js';
import { firstInSession } from '../src/session/marker.js';
import { sandbox, type Sandbox } from './helpers.js';

let sb: Sandbox;
beforeEach(async () => {
  sb = await sandbox();
});
afterEach(async () => {
  await sb.dispose();
});

const STATE = {
  schemaVersion: 1,
  artifacts: [
    { path: 'CLAUDE.md', hash: 'sha256:x', adapter: 'claude-code', kind: 'instructions' },
    { path: '.cursor/rules/a.mdc', hash: 'sha256:y', adapter: 'cursor', kind: 'instructions' },
  ],
};

async function rulegateRepo(): Promise<void> {
  await sb.put('.rulegate/rulegate.yaml', 'schemaVersion: 1\n');
  await sb.put('.rulegate/state.json', STATE);
  await sb.put('CLAUDE.md', '<!-- generated -->\n');
}

const at = (rel: string): string => path.join(sb.root, rel);

describe('generated-file guard (T108)', () => {
  it('denies an edit to a path state.json records, naming the recovery', async () => {
    await rulegateRepo();
    const d = await guard(at('CLAUDE.md'));
    expect(d?.kind).toBe('deny');
    expect(d && 'reason' in d ? d.reason : '').toMatch(
      /CLAUDE\.md is generated by Rulegate \(claude-code\).*rulegate sync --import/,
    );
  });

  it('denies creating a recorded path that is missing on disk', async () => {
    await rulegateRepo();
    expect((await guard(at('.cursor/rules/a.mdc')))?.kind).toBe('deny');
  });

  it('allows a file of the same name that is not recorded, and anything outside the repo', async () => {
    await rulegateRepo();
    await sb.put('docs/CLAUDE.md', 'mine');
    expect(await guard(at('docs/CLAUDE.md'))).toBeUndefined();
    expect(await guard(path.join(sb.claudeDir, 'CLAUDE.md'))).toBeUndefined();
    expect(await guard(at('.rulegate/rules/new.md'))).toBeUndefined();
  });

  it('allows everything in a project with no state.json', async () => {
    await sb.put('CLAUDE.md', 'x');
    expect(await guard(at('CLAUDE.md'))).toBeUndefined();
  });

  it("denies edits to sync's own bookkeeping", async () => {
    await rulegateRepo();
    expect((await guard(at('.rulegate/state.json')))?.kind).toBe('deny');
    expect((await guard(at('.rulegate/backup/CLAUDE.md')))?.kind).toBe('deny');
  });

  it('denies nothing on an unreadable state.json — check reports it, the guard must not wedge', async () => {
    await rulegateRepo();
    await sb.put('.rulegate/state.json', '<<<<<<< HEAD\n{}\n');
    expect(await guard(at('CLAUDE.md'))).toBeUndefined();
  });

  it('finds the repository root when Claude Code was opened in a subdirectory', async () => {
    await rulegateRepo();
    await mkdir(at('packages/app'), { recursive: true });
    expect((await guard(at('CLAUDE.md')))?.kind).toBe('deny');
  });

  it('sees through a symlinked project directory', async () => {
    await rulegateRepo();
    const link = path.join(path.dirname(sb.root), 'link');
    await symlink(sb.root, link);
    expect((await guard(path.join(link, 'CLAUDE.md')))?.kind).toBe('deny');
  });

  it('judges `..` textually, as the edit tool does, even after a symlink leaving the repo', async () => {
    await rulegateRepo();
    await mkdir(path.join(sb.claudeDir, 'far/deeper'), { recursive: true });
    await mkdir(at('docs'), { recursive: true });
    await symlink(path.join(sb.claudeDir, 'far/deeper'), at('docs/outlink'));
    expect((await guard(`${at('docs/outlink')}/../../CLAUDE.md`))?.kind).toBe('deny');
  });

  it("judges a file by its own repository's state.json, wherever the session is", async () => {
    await rulegateRepo();
    await mkdir(at('.git'));
    // A sibling repository, reached by absolute path.
    const sibling = path.join(path.dirname(sb.root), 'sibling');
    await mkdir(path.join(sibling, '.git'), { recursive: true });
    await mkdir(path.join(sibling, '.rulegate'), { recursive: true });
    await writeFile(path.join(sibling, '.rulegate/state.json'), JSON.stringify(STATE));
    expect((await guard(path.join(sibling, 'CLAUDE.md')))?.kind).toBe('deny');
    // A `.rulegate/` that is test data inside this repository is not an owner: `.git`
    // makes the repository root the owner, and it records no such path.
    await sb.put('fixtures/x/.rulegate/state.json', STATE);
    expect(await guard(at('fixtures/x/CLAUDE.md'))).toBeUndefined();
  });

  // T085: on APFS and NTFS `claude.md` IS `CLAUDE.md`, and the guard must say so exactly
  // where the filesystem does — which `probeCaseInsensitive` asks of the disk itself.
  const caseInsensitive = existsSync(fileURLToPath(new URL('../PACKAGE.JSON', import.meta.url)));
  it.runIf(caseInsensitive)(
    'denies another spelling of a recorded path where the filesystem folds case',
    async () => {
      await rulegateRepo();
      expect((await guard(at('claude.md')))?.kind).toBe('deny');
    },
  );
  it.runIf(!caseInsensitive)(
    'allows another spelling where the filesystem does not fold case',
    async () => {
      await rulegateRepo();
      expect(await guard(at('claude.md'))).toBeUndefined();
    },
  );
});

describe('cartographer reminder (T108)', () => {
  const once = (): ((s: string, k: string) => boolean) => {
    const seen = new Set<string>();
    return (s, k) => !seen.has(`${s}|${k}`) && Boolean(seen.add(`${s}|${k}`));
  };

  async function repo(): Promise<void> {
    await sb.put('src/features/auth/login.ts', 'x');
    await sb.put('src/features/cart/cart.ts', 'x');
    await sb.put('.claude/agent-memory/rulegate-feature-cartographer/cart.md', '# cart\n');
    sb.commit('2026-09-20');
  }

  it('reminds once per feature per session, and not for a mapped feature', async () => {
    await repo();
    const first = once();
    const r = await reminder(at('src/features/auth/login.ts'), sb.root, 's1', first);
    expect(r).toMatchObject({ kind: 'context' });
    expect(r && 'text' in r ? r.text : '').toContain(
      'ask rulegate:feature-cartographer how "auth" is built',
    );
    expect(await reminder(at('src/features/auth/other.ts'), sb.root, 's1', first)).toBeUndefined();
    expect(await reminder(at('src/features/auth/login.ts'), sb.root, 's2', first)).toMatchObject({
      kind: 'context',
    });
    expect(await reminder(at('src/features/cart/cart.ts'), sb.root, 's1', first)).toBeUndefined();
  });

  it('is silent for a new feature, a path outside feature directories, and when switched off', async () => {
    await repo();
    await sb.put('src/features/brand-new/x.ts', 'x');
    expect(await reminder(at('src/features/brand-new/x.ts'), sb.root, 's', once())).toBeUndefined();
    expect(await reminder(at('README.md'), sb.root, 's', once())).toBeUndefined();
    await sb.put('.claude/rulegate.json', { cartographerReminder: false });
    expect(await reminder(at('src/features/auth/login.ts'), sb.root, 's', once())).toBeUndefined();
  });
});

describe('session marker (P3)', () => {
  it('answers true once, then false', () => {
    const base = path.join(sb.root, 'markers');
    expect(firstInSession('s', 'src/a-b', base)).toBe(true);
    expect(firstInSession('s', 'src/a-b', base)).toBe(false);
    expect(firstInSession('s', 'src/a.b', base)).toBe(true);
    expect(readdirSync(base)).toHaveLength(2);
  });

  it('refuses a base that is a symlink rather than a real directory', async () => {
    const base = path.join(sb.root, 'markers');
    expect(firstInSession('s', 'k', base)).toBe(true);
    const linked = path.join(sb.root, 'linked');
    await symlink(base, linked);
    expect(firstInSession('s', 'other', linked)).toBe(false);
    expect(readdirSync(base)).toHaveLength(1);
  });
});

describe('dist/pre-edit.js', () => {
  const bin = fileURLToPath(new URL('../dist/pre-edit.js', import.meta.url));
  const run = (stdin: string, env: NodeJS.ProcessEnv = {}): { status: number; stdout: string } => {
    try {
      const stdout = execFileSync(process.execPath, [bin], {
        input: stdin,
        env: { ...process.env, CLAUDE_PROJECT_DIR: sb.root, ...env },
        encoding: 'utf8',
      });
      return { status: 0, stdout };
    } catch (e) {
      const err = e as { status: number; stdout: string };
      return { status: err.status, stdout: err.stdout };
    }
  };

  it('emits a PreToolUse deny for a generated file', async () => {
    await rulegateRepo();
    const { status, stdout } = run(
      JSON.stringify({ tool_name: 'Edit', tool_input: { file_path: at('CLAUDE.md') } }),
    );
    expect(status).toBe(0);
    const out = JSON.parse(stdout) as { hookSpecificOutput: Record<string, string> };
    expect(out.hookSpecificOutput.hookEventName).toBe('PreToolUse');
    expect(out.hookSpecificOutput.permissionDecision).toBe('deny');
  });

  it('resolves a relative file_path against the session cwd, and ~ against home, as the tool does', async () => {
    await rulegateRepo();
    await mkdir(at('docs'), { recursive: true });
    // CLAUDE_PROJECT_DIR is the repo; the session has `cd`-ed into docs/.
    expect(
      run(JSON.stringify({ cwd: at('docs'), tool_input: { file_path: '../CLAUDE.md' } })).stdout,
    ).toContain('"deny"');
    expect(run(JSON.stringify({ tool_input: { file_path: 'CLAUDE.md' } })).stdout).toContain(
      '"deny"',
    );
    expect(
      run(JSON.stringify({ tool_input: { file_path: '~/CLAUDE.md' } }), { HOME: sb.root }).stdout,
    ).toContain('"deny"');
  });

  it('exits 0 silently on garbage, empty or irrelevant input', async () => {
    await rulegateRepo();
    for (const stdin of ['not json', '', '{}', JSON.stringify({ tool_input: { file_path: 42 } })]) {
      expect(run(stdin)).toEqual({ status: 0, stdout: '' });
    }
  });
});
