import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  GIT_DENY,
  TODO_ENV,
  insertTaskRule,
  planSettings,
  planTaskRule,
} from '../src/lib/settings.js';
import { sandbox, type Sandbox } from './helpers.js';

describe('planSettings (T106, pure half of T109)', () => {
  it('plans every deny rule and the env flag for an absent file', () => {
    const p = planSettings(undefined);
    expect(p.status).toBe('changed');
    expect(p.denyAdded).toHaveLength(GIT_DENY.length);
    expect(p.env).toBe('added');
    expect(JSON.parse(p.next!)).toMatchObject({ env: { [TODO_ENV]: '1' } });
  });

  it('is idempotent: its own output plans nothing', () => {
    expect(planSettings(planSettings(undefined).next).status).toBe('unchanged');
  });

  it('merges, keeping allow rules, other keys and deny rules already there', () => {
    const p = planSettings(
      JSON.stringify({
        model: 'x',
        permissions: { allow: ['Bash(ls *)'], deny: ['Bash(git commit:*)', 'Read(.env)'] },
      }),
    );
    // `git commit:*` and `git commit *` are the same rule to Claude Code.
    expect(p.denyAdded).not.toContain('Bash(git commit *)');
    const next = JSON.parse(p.next!) as {
      model: string;
      permissions: { allow: string[]; deny: string[] };
    };
    expect(next.model).toBe('x');
    expect(next.permissions.allow).toEqual(['Bash(ls *)']);
    expect(next.permissions.deny.slice(0, 2)).toEqual(['Bash(git commit:*)', 'Read(.env)']);
  });

  it('leaves a user-set env value alone', () => {
    const p = planSettings(
      JSON.stringify({ env: { [TODO_ENV]: '0' }, permissions: { deny: [...GIT_DENY] } }),
    );
    expect(p).toMatchObject({ status: 'unchanged', env: 'conflict', current: '0' });
  });

  it('refuses invalid JSON rather than planning over it', () => {
    expect(planSettings('{ nope').status).toBe('invalid');
    expect(planSettings('[]').status).toBe('invalid');
  });
});

describe('planTaskRule', () => {
  let sb: Sandbox;
  beforeEach(async () => {
    sb = await sandbox();
  });
  afterEach(async () => {
    await sb.dispose();
  });

  it('plans a canonical rule, never an edit to the generated CLAUDE.md, in a Rulegate project', async () => {
    await sb.put('.rulegate/rulegate.yaml', 'schemaVersion: 1\n');
    await sb.put('CLAUDE.md', '<!-- generated by rulegate -->\n');
    const p = planTaskRule('project', sb.root, sb.claudeDir);
    expect(p).toMatchObject({ status: 'add', file: '.rulegate/rules/working-agreement.md' });
    expect(p.next).toMatch(/^---\ndescription: Working agreement\ntools: \[claude-code\]\n---\n/);
  });

  it('counts a rule added to .rulegate/rules/ but not yet synced as present', async () => {
    await sb.put('.rulegate/rules/work.md', '---\ndescription: w\n---\nUse TaskCreate.\n');
    expect(planTaskRule('project', sb.root, sb.claudeDir).status).toBe('present');
  });

  it('never creates a project CLAUDE.md outside a Rulegate project', () => {
    expect(planTaskRule('project', sb.root, sb.claudeDir).status).toBe('no-file');
  });

  it('creates the user CLAUDE.md when absent', () => {
    expect(planTaskRule('user', sb.root, sb.claudeDir)).toMatchObject({
      status: 'add',
      how: 'new file',
    });
  });

  it('files the rule under Operator preferences when there is one', () => {
    const { next, section } = insertTaskRule(
      '# A\n\n## Operator preferences\n\n- x\n\n## Later\n\ny\n',
    );
    expect(section).toBe('Operator preferences');
    expect(next.indexOf('TaskCreate')).toBeLessThan(next.indexOf('## Later'));
  });
});
