import { describe, expect, it } from 'vitest';
import { planAgents } from '../src/render/agents.js';
import { ADAPTER_API_VERSION, NOT_DETECTED, type Adapter } from '../src/adapter/adapter.js';
import { ALL_TOOLS } from '../src/model/selector.js';
import type { AgentFolder } from '../src/adapter/docs.js';
import type { Agent } from '../src/model/agent.js';
import type { JsonValue } from '../src/model/ids.js';

/**
 * T054: where an agent goes and what the user is told. The shipped adapters' own data is
 * covered by fixtures/agents-sync.
 */

const SOURCE = { url: 'https://example.test', title: 't', retrieved: '2026-09-29' };
function reader(name: string, folders: AgentFolder[], maxChars?: number): Adapter {
  return {
    name,
    apiVersion: ADAPTER_API_VERSION,
    detect: () => Promise.resolve(NOT_DETECTED),
    read: () => Promise.resolve({}),
    write: () => Promise.resolve([]),
    docs: {
      toolName: name,
      homepage: SOURCE.url,
      verifiedAgainst: { version: 'test', date: '2026-09-29' },
      files: [],
      agents: { folders, source: SOURCE, ...(maxChars === undefined ? {} : { maxChars }) },
    },
  };
}
const md = (dir: string, extensions: string[] = []): AgentFolder => ({
  dir,
  extension: '.md',
  format: 'markdown',
  extensions,
});
// A tool that reads a shared folder and a folder of its own, and restrictions only in the shared one.
const BOTH = reader('both', [md('.own/agents'), md('.shared/agents', ['tools'])]);
const SHARED = reader('shared', [md('.shared/agents', ['tools'])]);
const OWN = reader('own', [md('.own/agents')], 50);
const TOML = reader('toml', [
  { dir: '.toml/agents', extension: '.toml', format: 'toml', extensions: ['model', 'effort'] },
]);

function agent(
  id: string,
  extra: (readonly [string, JsonValue])[] = [],
  adapters: Agent['adapters'] = ALL_TOOLS,
  body = 'Do it.\n',
): Agent {
  const path = `.rulegate/agents/${id}.md`;
  return {
    id,
    path,
    name: id,
    description: `Agent ${id}.`,
    adapters,
    frontmatter: [['name', id], ['description', `Agent ${id}.`], ...extra],
    body,
    source: { file: path },
  };
}
const messages = (plan: ReturnType<typeof planAgents>) =>
  plan.warnings.map((w) => `${w.code} ${w.message}`);
const paths = (plan: ReturnType<typeof planAgents>) => plan.artifacts.map((a) => a.path).sort();

describe('agent placement (T054)', () => {
  it('names a tool that reads two chosen folders', () => {
    const plan = planAgents([agent('a')], [BOTH, OWN, SHARED], false);
    expect(paths(plan)).toEqual(['.own/agents/a.md', '.shared/agents/a.md']);
    expect(messages(plan)).toEqual([
      'W_AGENT_LOAD both reads .own/agents and .shared/agents, so it loads `a` twice',
    ]);
  });

  it('reaches a restricted agent only through folders that carry the restriction', () => {
    const plan = planAgents([agent('r', [['tools', 'Read']])], [BOTH, OWN], false);
    expect(paths(plan)).toEqual(['.shared/agents/r.md']);
    expect(messages(plan)).toEqual([
      'W_AGENT_RESTRICTED `r` restricts its tools, which own cannot be told, so own does not get it',
    ]);
  });

  it('names a tool `adapters:` leaves out that still reads a chosen folder', () => {
    const plan = planAgents(
      [agent('a', [], { kind: 'include', tools: ['shared'] })],
      [BOTH, SHARED],
      false,
    );
    expect(paths(plan)).toEqual(['.shared/agents/a.md']);
    expect(messages(plan)).toEqual([
      'W_AGENT_LOAD `a` leave both out with `adapters:`, but both also reads .shared/agents, where another tool gets it',
    ]);
  });

  it('writes Codex-style TOML, dropping a value TOML cannot hold as a string', () => {
    const plan = planAgents(
      [
        agent(
          't',
          [
            ['model', 'gpt-5'],
            ['effort', 3],
          ],
          ALL_TOOLS,
          'Say "hi" \\ bye.\n',
        ),
      ],
      [TOML],
      true,
    );
    expect(plan.artifacts[0]!.contents).toBe(
      '# generated by rulegate; edit .rulegate/ instead\n\nname = "t"\ndescription = "Agent t."\nmodel = "gpt-5"\ndeveloper_instructions = """\nSay \\"hi\\" \\\\ bye.\n"""\n',
    );
    expect(messages(plan)).toEqual([
      'W_AGENT_FIELD_DROPPED `effort` in `t` was left out of .toml/agents/: no tool that reads it understands the key',
    ]);
  });

  it('names a prompt over a tool’s cap', () => {
    const plan = planAgents([agent('long', [], ALL_TOOLS, `${'x'.repeat(60)}\n`)], [OWN], false);
    expect(messages(plan)).toEqual([
      'W_AGENT_OVER_LIMIT `long` has a prompt longer than the 50 characters own reads',
    ]);
  });

  it('is independent of adapter and agent order', () => {
    const agents = [agent('b', [['tools', 'Read']]), agent('a')];
    const one = planAgents(agents, [BOTH, OWN, SHARED, TOML], true);
    const two = planAgents([...agents].reverse(), [TOML, SHARED, OWN, BOTH], true);
    expect(two).toEqual(one);
  });
});

describe('agents in a nested .rulegate/ (T054)', () => {
  it('are not rendered, and say so', async () => {
    const { MemoryFileSystem } = await import('../src/io/memory.js');
    const { computePlan } = await import('../src/pipeline/plan.js');
    const fs = new MemoryFileSystem([
      ['.rulegate/rulegate.yaml', 'schemaVersion: 1\ntools:\n  - own\n'],
      ['packages/api/.rulegate/rulegate.yaml', 'schemaVersion: 1\ntools:\n  - own\n'],
      [
        'packages/api/.rulegate/agents/fix.md',
        '---\nname: fix\ndescription: Fix.\n---\n\nFix it.\n',
      ],
    ]);
    const plan = await computePlan({ repoRoot: '/repo', fs, adapters: [OWN] });
    expect(plan.artifacts.filter((a) => a.kind === 'subagent')).toEqual([]);
    expect(plan.warnings.map((w) => `${w.code} ${w.message}`)).toContain(
      'W_AGENT_NESTED agents in packages/api/.rulegate/agents/ are not rendered yet: `fix`',
    );
  });
});
