import { describe, expect, it } from 'vitest';
import { planCommands } from '../src/render/commands.js';
import { ADAPTER_API_VERSION, NOT_DETECTED, type Adapter } from '../src/adapter/adapter.js';
import { ALL_TOOLS } from '../src/model/selector.js';
import type { CommandsSupport } from '../src/adapter/docs.js';
import type { Command } from '../src/model/command.js';
import type { Skill } from '../src/model/skill.js';

/**
 * T053: what a command's copy says in each format, and what the user is told about what
 * could not be carried. The shipped adapters' own data is covered by fixtures/commands-sync.
 */

const SOURCE = { url: 'https://example.test', title: 't', retrieved: '2026-09-29' };
function tool(name: string, commands: Omit<CommandsSupport, 'source'>, skills = false): Adapter {
  return {
    name,
    apiVersion: ADAPTER_API_VERSION,
    detect: () => Promise.resolve(NOT_DETECTED),
    read: () => Promise.resolve({}),
    write: () => Promise.resolve([]),
    docs: {
      toolName: name,
      homepage: SOURCE.url,
      verifiedAgainst: { version: 'test', date: '2026-09-29' },
      files: [],
      commands: { ...commands, source: SOURCE },
      ...(skills ? { skills: { dirs: [`.${name}/skills`], extensions: [], source: SOURCE } } : {}),
    },
  };
}
const MD = tool(
  'md',
  {
    dir: '.md/commands',
    extension: '.md',
    format: 'markdown',
    arguments: '$ARGUMENTS',
    extensions: [],
  },
  true,
);
const TOML = tool('toml', {
  dir: '.toml/commands',
  extension: '.toml',
  format: 'toml',
  arguments: '{{args}}',
  extensions: [],
});
const PROMPT = tool('prompt', {
  dir: '.prompt',
  extension: '.prompt.md',
  format: 'markdown',
  arguments: '${input:args}',
  extensions: [],
});
const PLAIN = tool('plain', {
  dir: '.plain/workflows',
  extension: '.md',
  format: 'markdown-plain',
  extensions: [],
  maxChars: 80,
});

function command(id: string, body: string, tools: Command['tools'] = ALL_TOOLS): Command {
  const path = `.rulegate/commands/${id}.md`;
  return {
    id,
    path,
    description: `Run ${id}.`,
    tools,
    frontmatter: [['description', `Run ${id}.`]],
    body,
    source: { file: path },
  };
}
const contentsOf = (plan: ReturnType<typeof planCommands>, path: string) =>
  plan.artifacts.find((a) => a.path === path)?.contents;
const messages = (plan: ReturnType<typeof planCommands>) =>
  plan.warnings.map((w) => `${w.code} ${w.message}`);

describe('command rendering (T053)', () => {
  it('escapes TOML so no body can end the string early or change what is read', () => {
    const plan = planCommands(
      [command('esc', 'Quote """ and \\ and a bell \u0007 then {{args}} and $ARGUMENTS.\n')],
      [],
      [TOML],
      false,
    );
    expect(contentsOf(plan, '.toml/commands/esc.toml')).toBe(
      'description = "Run esc."\nprompt = """\nQuote \\"\\"\\" and \\\\ and a bell \\u0007 then {{args}} and {{args}}.\n"""\n',
    );
  });

  it('writes a `$` in a spelling literally, never as a replacement pattern', () => {
    const plan = planCommands([command('a', 'Use $ARGUMENTS now.\n')], [], [PROMPT], false);
    expect(contentsOf(plan, '.prompt/a.prompt.md')).toBe(
      '---\ndescription: Run a.\n---\n\nUse ${input:args} now.\n',
    );
  });

  it('leaves positional placeholders and $ARGUMENTS[N] alone for the one tool they are for', () => {
    const plan = planCommands(
      [command('pos', 'Compare $1 with $ARGUMENTS[0].\n', { kind: 'include', tools: ['md'] })],
      [],
      [MD, TOML],
      false,
    );
    expect(plan.artifacts.map((a) => a.path)).toEqual(['.md/commands/pos.md']);
    expect(contentsOf(plan, '.md/commands/pos.md')).toContain('Compare $1 with $ARGUMENTS[0].');
  });

  it('puts the description first where a tool reads no frontmatter, and says when it is too long', () => {
    const plan = planCommands(
      [command('short', 'Go.\n'), command('long', `${'x'.repeat(100)}\n`)],
      [],
      [PLAIN],
      true,
    );
    expect(contentsOf(plan, '.plain/workflows/short.md')).toBe(
      '<!-- generated by rulegate; edit .rulegate/ instead -->\n\nRun short.\n\nGo.\n',
    );
    expect(messages(plan)).toEqual([
      'W_COMMAND_OVER_LIMIT `long` is longer than the 80 characters plain reads of a command',
    ]);
  });

  it('names a command that a skill of the same name also answers, only where both reach', () => {
    const skill = { id: 'deploy', tools: ALL_TOOLS } as unknown as Skill;
    const plan = planCommands([command('deploy', 'Ship.\n')], [skill], [MD, TOML], false);
    expect(messages(plan)).toEqual([
      'W_COMMAND_SHADOWED `deploy` is both a skill and a command for md, so two things answer the same /name',
    ]);
  });

  it('renders nothing without commands or without a tool that has them', () => {
    expect(planCommands([], [], [MD], true).artifacts).toEqual([]);
    expect(planCommands([command('a', 'x\n')], [], [], true).artifacts).toEqual([]);
  });

  it('is independent of adapter and command order', () => {
    const cmds = [command('b', 'B $ARGUMENTS\n'), command('a', 'A\n')];
    const one = planCommands(cmds, [], [MD, TOML, PLAIN, PROMPT], true);
    const two = planCommands([...cmds].reverse(), [], [PROMPT, PLAIN, TOML, MD], true);
    expect(two).toEqual(one);
  });
});

describe('commands in a nested .rulegate/ (T053)', () => {
  it('are not rendered, and say so', async () => {
    const { MemoryFileSystem } = await import('../src/io/memory.js');
    const { computePlan } = await import('../src/pipeline/plan.js');
    const md = '---\ndescription: Deploy.\n---\n\nShip it.\n';
    const fs = new MemoryFileSystem([
      ['.rulegate/rulegate.yaml', 'schemaVersion: 1\ntools:\n  - md\n'],
      ['packages/api/.rulegate/rulegate.yaml', 'schemaVersion: 1\ntools:\n  - md\n'],
      ['packages/api/.rulegate/commands/deploy.md', md],
    ]);
    const plan = await computePlan({ repoRoot: '/repo', fs, adapters: [MD] });
    expect(plan.artifacts.filter((a) => a.kind === 'command')).toEqual([]);
    expect(plan.warnings.map((w) => `${w.code} ${w.message}`)).toContain(
      'W_COMMAND_NESTED commands in packages/api/.rulegate/commands/ are not rendered yet: `deploy`',
    );
  });
});
