import { describe, expect, it } from 'vitest';
import { importMcpJson, stripJsonc } from '../src/import/mcp.js';
import type { ReferenceParse } from '../src/import/mcp.js';
import { envRef } from '../src/model/mcp.js';

/** The Claude Code dialect, the simplest of the three. */
function parseReference(raw: string): ReferenceParse | undefined {
  const m = /^\$\{([A-Za-z_][A-Za-z0-9_]*)\}$/.exec(raw);
  return m === null ? undefined : { kind: 'ref', ref: envRef(m[1]!) };
}

function importJson(body: string) {
  return importMcpJson(body, { serversKey: 'mcpServers', parseReference, file: '.mcp.json' });
}

describe('importMcpJson — T041', () => {
  it('inverts a stdio server and a remote one', () => {
    const { servers, warnings } = importJson(
      JSON.stringify({
        mcpServers: {
          memory: { command: 'npx', args: ['-y', 'server-memory'] },
          github: { type: 'sse', url: 'https://x.test/mcp', headers: { Auth: '${TOKEN}' } },
        },
      }),
    );
    expect(warnings).toEqual([]);
    expect(servers.map((s) => s.id)).toEqual(['github', 'memory']);
    expect(servers[1]!.transport).toEqual({
      kind: 'stdio',
      command: 'npx',
      args: ['-y', 'server-memory'],
    });
    expect(servers[0]!.transport).toEqual({ kind: 'sse', url: 'https://x.test/mcp' });
    expect(servers[0]!.headers['Auth']).toEqual({ kind: 'env', name: 'TOKEN' });
  });

  it('converts a literal credential to a reference and never quotes it', () => {
    const { servers, warnings } = importJson(
      JSON.stringify({
        mcpServers: {
          gh: { command: 'x', env: { GITHUB_TOKEN: 'ghp_0123456789abcdefghijklmnopqrstuvwx' } },
        },
      }),
    );
    expect(servers[0]!.env['GITHUB_TOKEN']).toEqual({ kind: 'env', name: 'GITHUB_TOKEN' });
    expect(warnings).toHaveLength(1);
    // The message names the key and the variable, never the credential. A scanner that
    // prints what it found commits the secret to a different file (T037).
    expect(warnings[0]).not.toContain('ghp_');
  });

  it('refuses a whole server rather than half-importing a literal that is not a secret', () => {
    // `env: { NODE_ENV: "production" }` is ordinary and canonical cannot express it:
    // `McpServer.env` is `Record<string, EnvRef>`. Converting would silently repoint the
    // server at the user's shell; dropping the key would lose content.
    const { servers, warnings } = importJson(
      JSON.stringify({ mcpServers: { app: { command: 'x', env: { NODE_ENV: 'production' } } } }),
    );
    expect(servers).toEqual([]);
    expect(warnings[0]).toContain('NODE_ENV');
    expect(warnings[0]).toContain('skipped');
  });

  it('refuses a reference with text around it, naming that case specifically', () => {
    // `"Authorization": "Bearer ${TOKEN}"` is how almost every real file spells it, and a
    // canonical header value is a bare reference — the prefix has nowhere to live.
    const { servers, warnings } = importJson(
      JSON.stringify({
        mcpServers: {
          gh: { url: 'https://x.test', headers: { Authorization: 'Bearer ${TOKEN}' } },
        },
      }),
    );
    expect(servers).toEqual([]);
    expect(warnings[0]).toContain('embeds a variable reference');
  });

  it('refuses `${NAME:-default}` and `${input:id}`', () => {
    for (const value of ['${TOKEN:-fallback}', '${input:token}']) {
      const { servers, warnings } = importJson(
        JSON.stringify({ mcpServers: { gh: { url: 'https://x.test', headers: { A: value } } } }),
      );
      expect(servers).toEqual([]);
      expect(warnings).toHaveLength(1);
    }
  });

  it('refuses a transport canonical has no arm for', () => {
    // Claude Code documents `ws`. Importing it as `http` would point a streamable-HTTP
    // client at a WebSocket endpoint.
    const { servers, warnings } = importJson(
      JSON.stringify({ mcpServers: { s: { type: 'ws', url: 'wss://x.test' } } }),
    );
    expect(servers).toEqual([]);
    expect(warnings[0]).toContain('ws');
  });

  it('treats `streamable-http` as `http`', () => {
    const { servers } = importJson(
      JSON.stringify({ mcpServers: { s: { type: 'streamable-http', url: 'https://x.test' } } }),
    );
    expect(servers[0]!.transport).toEqual({ kind: 'http', url: 'https://x.test' });
  });

  it('skips Rulegate’s own marker key rather than importing it as a server', () => {
    const { servers } = importJson(
      JSON.stringify({ mcpServers: { '//': 'generated by rulegate', s: { command: 'x' } } }),
    );
    expect(servers.map((s) => s.id)).toEqual(['s']);
  });

  it('preserves keys it does not interpret', () => {
    const { servers } = importJson(
      JSON.stringify({ mcpServers: { s: { command: 'x', timeout: 30, cwd: './sub' } } }),
    );
    expect(servers[0]!.unknown).toEqual({ cwd: './sub', timeout: 30 });
  });

  it('warns rather than throwing on a file that is not JSON at all', () => {
    const { servers, warnings } = importJson('not json {{{');
    expect(servers).toEqual([]);
    expect(warnings[0]).toContain('could not be parsed');
  });

  it('reports the top-level `inputs` array as not imported', () => {
    const { warnings } = importJson(JSON.stringify({ inputs: [{ id: 'k' }], mcpServers: {} }));
    expect(warnings[0]).toContain('inputs');
  });
});

describe('stripJsonc — T041', () => {
  it('removes line and block comments and trailing commas', () => {
    const text = `{
      // a line comment
      "a": 1, /* inline */
      "b": [1, 2,],
    }`;
    expect(JSON.parse(stripJsonc(text))).toEqual({ a: 1, b: [1, 2] });
  });

  it('leaves comment-like and comma-like text inside strings alone', () => {
    // The whole reason this is string-aware. A URL contains `//`, and stripping it there
    // would silently truncate every remote server's endpoint.
    const text = '{"url": "https://x.test/a,b", "c": "/* not a comment */"}';
    expect(JSON.parse(stripJsonc(text))).toEqual({
      url: 'https://x.test/a,b',
      c: '/* not a comment */',
    });
  });

  it('is a no-op on plain JSON', () => {
    const text = '{"a":[1,2],"b":"x"}';
    expect(stripJsonc(text)).toBe(text);
  });
});
