import { describe, expect, it } from 'vitest';
import type { Canonical } from '@rulegate/adapter-kit';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';
import { CONFIG_FILE, RULES_DIR, opencode } from '../src/index.js';

describe('opencode write()', () => {
  it('matches the golden fixture byte for byte', async () => {
    await expectFixtureMatch('opencode', opencode);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent('opencode', opencode);
  });

  it('excludes rules that target other tools', async () => {
    const actual = await renderFixture('opencode', opencode);
    expect([...actual.values()].join('\n')).not.toContain('This rule must not reach opencode');
    expect([...actual.keys()]).not.toContain(`${RULES_DIR}/30-cursor-only.md`);
  });

  it('writes a config OpenCode will accept: $schema and instructions, nothing else', async () => {
    // OpenCode's schema rejects unknown keys, so the `"//"` marker every other generated
    // JSON file carries would make it refuse to start.
    const actual = await renderFixture('opencode', opencode);
    const config = JSON.parse(actual.get(CONFIG_FILE)!) as Record<string, unknown>;
    expect(Object.keys(config)).toEqual(['$schema', 'instructions']);
    expect(config['instructions']).toEqual([
      `${RULES_DIR}/10-style.md`,
      `${RULES_DIR}/20-testing.md`,
      `${RULES_DIR}/40-sources.md`,
    ]);
  });

  it('keeps the marker off the config even when the manifest asks for it', async () => {
    const ctx = await contextFor('opencode/input', opencode);
    expect(ctx.canonical.manifest.options.marker).toBe(true);
    const config = (await opencode.write(ctx)).find((a) => a.path === CONFIG_FILE);
    expect(config?.contents).not.toContain('generated by rulegate');
  });

  it('never plans the root opencode.json, which belongs to the user', async () => {
    const actual = await renderFixture('opencode', opencode);
    expect([...actual.keys()].filter((p) => !p.startsWith('.opencode/'))).toEqual([]);
  });

  it("keeps a scoped rule's scope visible as prose", async () => {
    const actual = await renderFixture('opencode', opencode);
    expect(actual.get(`${RULES_DIR}/40-sources.md`)).toContain(
      '**Applies to:** `src/**/*.ts`, `*.proto`',
    );
  });

  it('records which rule produced each rule file, and none for the config', async () => {
    const ctx = await contextFor('opencode/input', opencode);
    const artifacts = await opencode.write(ctx);
    expect(artifacts.map((a) => [a.path, a.provenance?.ruleIds])).toEqual([
      [`${RULES_DIR}/10-style.md`, ['10-style']],
      [`${RULES_DIR}/20-testing.md`, ['20-testing']],
      [`${RULES_DIR}/40-sources.md`, ['40-sources']],
      [CONFIG_FILE, undefined],
    ]);
  });

  it('emits no file when no rule targets this tool', async () => {
    const ctx = await contextFor('opencode/input', opencode);
    const canonical: Canonical = { ...ctx.canonical, rules: [] };
    expect(await opencode.write({ ...ctx, canonical })).toEqual([]);
  });
});
