import {
  ADAPTER_API_VERSION,
  RulegateError,
  appliesRepoWide,
  basenamePosix,
  claimRuleId,
  detected,
  importConcatenated,
  importRuleId,
  importedRule,
  finalizeArtifact,
  isCanonicalSource,
  renderConcatenated,
  selects,
  slugForId,
  sortRules,
  withHtmlMarker,
  type Adapter,
  type AdapterContext,
  type Artifact,
  type Canonical,
  type DetectResult,
  type ImportResult,
  type RuleDocument,
} from '@rulegate/adapter-kit';
import {
  assertRenderable,
  frontmatterFor,
  parseInstructions,
  renderInstructionsFrontmatter,
} from './instructions.js';
import { MCP_FILE, importMcpConfig, renderMcpJson } from './mcp.js';
import { docs } from './docs.js';

export const REPO_INSTRUCTIONS = '.github/copilot-instructions.md';
export const INSTRUCTIONS_DIR = '.github/instructions';

// `.github` alone is not evidence — nearly every repository has one, and a detector that
// fires on it reports Copilot everywhere and means nothing.
// `.vscode/mcp.json` is evidence; a bare `.vscode/` is not. The directory is as ubiquitous
// as `.github/`, which was rejected as evidence for exactly this reason — but an `mcp.json`
// inside it is a deliberate MCP configuration, and without it `collectImports` never hands
// this adapter a repository whose only AI config is that file.
const DETECTION_PATHS = [REPO_INSTRUCTIONS, INSTRUCTIONS_DIR, MCP_FILE] as const;

async function detect(ctx: AdapterContext): Promise<DetectResult> {
  const evidence: string[] = [];
  for (const path of DETECTION_PATHS) {
    if (await ctx.fs.exists(path)) evidence.push(path);
  }
  return detected(evidence);
}

/**
 * The two mechanisms are read the way they are written: repo-wide rules concatenated in
 * one file, glob-scoped rules one per file. `parseGlobs` is false for the repository-wide
 * file because nothing there can be glob-scoped — it is rendered with `showGlobs: false`,
 * so a bold "Applies to" line in it is the user's own prose, not our marker.
 */
async function read(ctx: AdapterContext): Promise<Partial<Canonical>> {
  const rules: RuleDocument[] = [];
  const taken = new Set<string>();

  if (!isCanonicalSource(ctx.canonical.manifest, REPO_INSTRUCTIONS)) {
    const contents = await ctx.fs.tryReadFile(REPO_INSTRUCTIONS);
    if (contents !== undefined) {
      for (const rule of importConcatenated({
        file: REPO_INSTRUCTIONS,
        contents,
        headingLevel: 2,
        parseGlobs: false,
        idFallback: 'copilot',
      })) {
        rules.push({ ...rule, id: claimRuleId(rule.id, taken) });
      }
    }
  }

  for (const path of await ctx.fs.glob(`${INSTRUCTIONS_DIR}/**/*.instructions.md`)) {
    if (isCanonicalSource(ctx.canonical.manifest, path)) continue;
    const contents = await ctx.fs.tryReadFile(path);
    if (contents === undefined) continue;

    const parsed = parseInstructions(contents);
    if (parsed.body === '' && parsed.description === undefined) continue;

    const base = basenamePosix(path).replace(/\.instructions\.md$/i, '');
    rules.push(
      importedRule({
        id: claimRuleId(importRuleId(base, 'copilot'), taken),
        ...(parsed.description === undefined ? {} : { description: parsed.description }),
        globs: parsed.applyTo,
        body: parsed.body,
        unknown: parsed.unknown,
        source: { file: path, line: 1 },
      }),
    );
  }

  return {
    ...(rules.length === 0 ? {} : { rules }),
    ...(await readMcp(ctx)),
  };
}

/**
 * The MCP half, guarded separately from the rules half.
 *
 * A repository can hold `.vscode/mcp.json` and no rules at all, so folding this into the rules
 * return would import no servers there — the mirror of the bug T038 found on the write
 * side, where one early return covered the whole adapter.
 */
async function readMcp(ctx: AdapterContext): Promise<ImportResult> {
  if (isCanonicalSource(ctx.canonical.manifest, MCP_FILE)) return {};
  const contents = await ctx.fs.tryReadFile(MCP_FILE);
  if (contents === undefined) return {};
  const { servers, warnings } = importMcpConfig(contents);
  return {
    ...(servers.length === 0 ? {} : { mcpServers: servers }),
    ...(warnings.length === 0 ? {} : { warnings }),
  };
}

function instructionsPath(rule: RuleDocument): string {
  return `${INSTRUCTIONS_DIR}/${slugForId(rule.id)}.instructions.md`;
}

function renderInstructions(rule: RuleDocument, marker: boolean): string {
  assertRenderable(rule);
  // The marker follows the frontmatter rather than leading the file: YAML frontmatter must
  // occupy the first bytes, so a leading HTML comment would stop it being frontmatter.
  const head = renderInstructionsFrontmatter(frontmatterFor(rule));
  const body = rule.body.replace(/\n+$/, '');
  return marker
    ? `${head}\n<!-- generated by rulegate; edit .rulegate/ instead -->\n\n${body}`
    : `${head}\n${body}`;
}

/**
 * Copilot is the only MVP tool with a native per-path mechanism, so it is the only one
 * where glob scoping survives the round trip. Each rule lands in exactly one of the two
 * files — repo-wide rules in the always-on file, glob-scoped rules in their own
 * `.instructions.md` — because Copilot applies both when they match, so writing a rule to
 * both would send it twice.
 */
async function write(ctx: AdapterContext): Promise<readonly Artifact[]> {
  const { canonical } = ctx;
  const marker = canonical.manifest.options.marker;
  const rules = sortRules(canonical.rules.filter((r) => selects(r.frontmatter.tools, 'copilot')));

  const artifacts: Artifact[] = [];

  // Each artifact carries its own guards. This used to be one `rules.length === 0` early
  // return covering the whole adapter, which was right while rules were the only output
  // and became wrong the moment MCP arrived (T038 found the same hole in the other two):
  // a repository whose only canonical content is `.rulegate/mcp/servers.yaml` still has
  // a `.vscode/mcp.json` to generate.
  const repoWide = rules.filter((r) => appliesRepoWide(r));
  if (repoWide.length > 0 && !isCanonicalSource(canonical.manifest, REPO_INSTRUCTIONS)) {
    artifacts.push(
      finalizeArtifact({
        path: REPO_INSTRUCTIONS,
        // showGlobs is false here and true for the concatenating adapters: every rule in
        // this file is repo-wide by construction, so there is no scope to state.
        contents: withHtmlMarker(
          renderConcatenated(repoWide, { headingLevel: 2, showGlobs: false }),
          marker,
        ),
        adapter: 'copilot',
        kind: 'rules',
        provenance: { ruleIds: repoWide.map((r) => r.id) },
      }),
    );
  }

  const claimed = new Map<string, string>();
  for (const rule of rules.filter((r) => !appliesRepoWide(r))) {
    const path = instructionsPath(rule);

    const previous = claimed.get(path);
    if (previous !== undefined) {
      // Two rule ids slugging to one filename would silently drop one rule's content.
      throw new RulegateError({
        code: 'E_ARTIFACT_PATH_CONFLICT',
        message: `rules \`${previous}\` and \`${rule.id}\` both generate ${path}`,
        source: rule.source,
        hint: 'rename one of the rules so their generated filenames differ',
      });
    }
    claimed.set(path, rule.id);

    if (isCanonicalSource(canonical.manifest, path)) continue;

    artifacts.push(
      finalizeArtifact({
        path,
        contents: renderInstructions(rule, marker),
        adapter: 'copilot',
        kind: 'rules',
        provenance: { ruleIds: [rule.id] },
      }),
    );
  }

  // No `provenance`: no canonical rule contributed to this file, and claiming one would
  // mislead `doctor` and T045's merge, both of which read `ruleIds` as a real mapping.
  const mcp = renderMcpJson(canonical.mcpServers, marker);
  if (mcp !== '' && !isCanonicalSource(canonical.manifest, MCP_FILE)) {
    artifacts.push(
      finalizeArtifact({ path: MCP_FILE, contents: mcp, adapter: 'copilot', kind: 'mcp' }),
    );
  }

  return Promise.resolve(artifacts);
}

export const copilot: Adapter = {
  name: 'copilot',
  apiVersion: ADAPTER_API_VERSION,
  detect,
  read,
  write,
  docs,
};

export default copilot;
export { docs, frontmatterFor, renderInstructionsFrontmatter, MCP_FILE, renderMcpJson };
