import { describe, expect, it } from 'vitest';
import { envRef, type Canonical, type McpServer } from '@rulegate/adapter-kit';
import { codex, MCP_FILE, renderConfigToml } from '../src/index.js';
import { unrepresentableServers } from '../src/mcp.js';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';

const FIXTURE = 'codex-mcp';

async function render(mutate: (c: Canonical) => Canonical = (c) => c): Promise<string | undefined> {
  const ctx = await contextFor(`${FIXTURE}/input`, codex);
  const artifacts = await codex.write({ ...ctx, canonical: mutate(ctx.canonical) });
  return artifacts.find((a) => a.path === MCP_FILE)?.contents;
}

async function servers(): Promise<readonly McpServer[]> {
  return (await contextFor(`${FIXTURE}/input`, codex)).canonical.mcpServers;
}

function serverAt(list: readonly McpServer[], id: string): McpServer {
  const found = list.find((s) => s.id === id);
  if (found === undefined) throw new Error(`fixture has no server \`${id}\``);
  return found;
}

describe('codex MCP output (T047)', () => {
  it('matches the hand-written golden byte for byte', async () => {
    await expectFixtureMatch(FIXTURE, codex);
  });

  it('is idempotent across repeated renders', async () => {
    await expectIdempotent(FIXTURE, codex);
  });

  it('generates MCP for a repository with servers and no rules', async () => {
    const actual = await renderFixture(FIXTURE, codex);
    expect([...actual.keys()]).toEqual([MCP_FILE]);
  });

  it('renders the artifact as kind `mcp` with no provenance', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, codex);
    const artifact = (await codex.write(ctx)).find((a) => a.path === MCP_FILE);

    expect(artifact?.kind).toBe('mcp');
    expect(artifact?.provenance).toBeUndefined();
  });

  it('skips a server scoped to another tool, a disabled one and a global one', async () => {
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('cursor-only');
    expect(contents).not.toContain('disabled-server');
    expect(contents).not.toContain('user-global');
  });

  it('writes the tables in id order, which for TOML is the file order', async () => {
    const contents = (await render()) ?? '';
    const headers = [...contents.matchAll(/^\[mcp_servers\.(.+)\]$/gm)].map((m) => m[1]);
    // Sub-tables included deliberately. TOML binds them by dotted path, not by position, so
    // the file would still parse with them anywhere — this pins the *layout*, which is what
    // makes the output reviewable by eye, and the layout is a byte contract like any other.
    expect(headers).toEqual([
      'alpha-http',
      'alpha-http.env_http_headers',
      'linear-sse',
      'linear-sse.env_http_headers',
      'zebra-stdio',
    ]);
  });

  it('writes one order whatever order the servers arrive in', async () => {
    // **The golden cannot see `selectMcpServers`' sort, and T046 predicted that it could.**
    // Its note said TOML would be the first target where insertion order is file order and
    // a fixture would therefore guard the sort. It is not: `parseMcpServers` already sorts
    // by id at parse time, so a fixture's servers reach the adapter sorted however the
    // YAML was written, and deleting the sort passes all 46 tests here. That is the
    // twenty-second inert guard's shape exactly — a normalization elsewhere in the pipeline
    // satisfying the assertion — arriving this time from *upstream* rather than downstream.
    //
    // So the sort's guards are this test and the one in `core/test/mcp.test.ts`, both of
    // which reverse the input by hand. It is still load-bearing: `selectMcpServers` is
    // public API in the frozen kit, and a caller that builds servers programmatically
    // rather than parsing them — T048's importer, an external adapter — gets whatever
    // order it built.
    const list = await servers();
    const reversed: readonly McpServer[] = [...list].reverse();
    expect(renderConfigToml(reversed, true)).toBe(renderConfigToml(list, true));
    expect(renderConfigToml(reversed, true)).toContain('[mcp_servers.alpha-http]\ntimeout');
  });

  it('carries a `#` comment marker, not an HTML one', async () => {
    // `withHashMarker` was written at T005 and had no call site for every task since; the
    // note in T005 earmarked it for exactly this file.
    const contents = (await render()) ?? '';
    expect(contents.startsWith('# generated by rulegate; edit .rulegate/ instead\n')).toBe(true);
    expect(contents).not.toContain('<!--');
  });

  it('omits the marker when the manifest disables it', async () => {
    const contents =
      (await render((c) => ({
        ...c,
        manifest: { ...c.manifest, options: { ...c.manifest.options, marker: false } },
      }))) ?? '';
    expect(contents).not.toContain('generated by rulegate');
    expect(contents.startsWith('[mcp_servers.alpha-http]')).toBe(true);
  });

  it('maps a same-named env reference onto `env_vars`, never a value', async () => {
    // Codex has no variable substitution at all, so the reference cannot be a value. It
    // becomes a different key with different semantics: whitelist the name for forwarding.
    const contents = (await render()) ?? '';
    expect(contents).toContain('env_vars = ["GITHUB_TOKEN"]');
    expect(contents).not.toContain('env:GITHUB_TOKEN');
    expect(contents).not.toContain('${');
    expect(contents).not.toContain('[mcp_servers.zebra-stdio.env]');
  });

  /**
   * T096. `bearer_token_env_var` was the obvious mapping and it was wrong: Codex expands it
   * to `Authorization: Bearer $VAR`, supplying the scheme itself, so the variable holds a
   * bare token — while `.mcp.json` renders the same canonical entry as `"${VAR}"`, whose
   * variable must hold the whole `Bearer <token>`. One canonical header could not be right
   * for both. `env_http_headers` sets the header to the raw value, which is what a canonical
   * header reference has always meant.
   */
  it('maps a header reference onto `env_http_headers`, not `bearer_token_env_var`', async () => {
    const contents = (await render()) ?? '';
    expect(contents).toContain(
      '[mcp_servers.linear-sse.env_http_headers]\nAuthorization = "LINEAR_API_KEY"',
    );
    expect(contents).toContain(
      '[mcp_servers.alpha-http.env_http_headers]\nAuthorization = "DOCS_API_KEY_PRODUCTION"',
    );
    expect(contents).not.toContain('bearer_token_env_var');
  });

  it('loses the sse distinction, because Codex documents no discriminator', async () => {
    // The documented, deliberate loss: lossy but still a working server, so a `warn` note
    // rather than a refusal — the split Cursor's missing `type` key established.
    const contents = (await render()) ?? '';
    expect(contents).not.toContain('transport');
    expect(contents).not.toContain('type =');
    // The url is all that is left of it, and `sse` survives only as part of that string.
    expect(contents).toContain('url = "https://mcp.linear.app/sse"');
    // So an sse server and an http one differ only in their url and their unknown keys.
    // Asserted so that a `type` key added here later has to change this test deliberately.
    const sse = /\[mcp_servers\.linear-sse\]\n([^[]*)/.exec(contents)?.[1] ?? '';
    expect(
      sse
        .trim()
        .split('\n')
        .map((l) => l.split(' = ')[0]),
    ).toEqual(['url']);
  });

  it('re-emits keys Rulegate does not interpret', async () => {
    // An integer, not a quoted string: TOML has real number syntax and quoting it would
    // change the type Codex reads back.
    expect((await render()) ?? '').toContain('timeout = 600000');
  });

  it('renders nothing when no server targets this tool', async () => {
    const ctx = await contextFor(`${FIXTURE}/input`, codex);
    expect(await codex.write({ ...ctx, canonical: { ...ctx.canonical, mcpServers: [] } })).toEqual(
      [],
    );
  });

  it('still refuses to write over a canonical source', async () => {
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: [MCP_FILE] },
    }));
    expect(contents).toBeUndefined();
  });

  it('generates the config even when AGENTS.md is the canonical source', async () => {
    // The sharper half of T046's early-return hole. Using AGENTS.md as canonical is the
    // ordinary way to use Codex, and before T047 that path returned `[]` for the whole
    // adapter — canonical MCP parsed, validated, and silently unreachable.
    const contents = await render((c) => ({
      ...c,
      manifest: { ...c.manifest, canonicalSources: ['AGENTS.md'] },
    }));
    expect(contents).toContain('[mcp_servers.alpha-http]');
  });
});

describe('codex omits what Codex cannot say, and says so (T047, changed by T083)', () => {
  it('omits a renamed environment reference and names it in the file', async () => {
    // **T083 changed this from a refusal to an omission.** Throwing put an error in
    // `computePlan`, and `sync` writes nothing while any error stands — so one server
    // Codex could not express took down the whole run: no CLAUDE.md, no AGENTS.md, and
    // not even the servers every tool *can* express. Reproduced on a hand-written
    // servers.yaml, which is the documented way to use this feature.
    const list = await servers();
    const stdio = serverAt(list, 'zebra-stdio');
    const renamed: McpServer = { ...stdio, env: { API_KEY: envRef('MY_TOKEN') } };

    const rendered = renderConfigToml([renamed, serverAt(list, 'alpha-http')], true);

    // Omitted, not silently dropped: the explanation is in the generated file, which is
    // where the consequence is. It is committed, it appears in `check`'s diff, and a
    // reader of .codex/config.toml learns why a server they configured is missing.
    expect(rendered).toContain('# omitted: `zebra-stdio`');
    expect(rendered).toContain('differently-named variable');
    expect(rendered).not.toContain('[mcp_servers.zebra-stdio]');

    // And the rest of the file still renders. This is the whole point of the change.
    expect(rendered).toContain('[mcp_servers.alpha-http]');
  });

  it('renders a same-named reference normally', async () => {
    // The control. An assertion that something is omitted passes against a renderer that
    // omits everything (T020's lesson), so the expressible case must still appear.
    const list = await servers();
    const stdio = serverAt(list, 'zebra-stdio');
    expect(renderConfigToml([stdio], true)).toContain('env_vars = ["GITHUB_TOKEN"]');
    expect(renderConfigToml([stdio], true)).not.toContain('# omitted');
  });

  /**
   * This used to be a refusal: `bearer_token_env_var` is Authorization-only, so any other
   * header meant omitting the whole server. `env_http_headers` takes any header name, so the
   * refusal is gone with the key that caused it (T096) — the case is kept as the proof.
   */
  it('writes a reference in any header, not only Authorization', async () => {
    const list = await servers();
    const http = serverAt(list, 'alpha-http');
    const other: McpServer = { ...http, headers: { 'X-Api-Key': envRef('DOCS_API_KEY') } };

    const rendered = renderConfigToml([other, serverAt(list, 'zebra-stdio')], true);
    expect(rendered).not.toContain('# omitted');
    expect(rendered).toContain(
      '[mcp_servers.alpha-http.env_http_headers]\nX-Api-Key = "DOCS_API_KEY"',
    );
    expect(rendered).toContain('[mcp_servers.zebra-stdio]');
  });

  it('keeps a header name exactly as written, whatever its casing', async () => {
    const list = await servers();
    const http = serverAt(list, 'alpha-http');
    const lower: McpServer = { ...http, headers: { authorization: envRef('DOCS_API_KEY') } };

    // Lower-cased on the way in, lower-cased on the way out. Codex builds the header from
    // this name directly, and header names are case-insensitive on the wire, so there is
    // nothing to normalize and normalizing would lose what the user wrote.
    expect(renderConfigToml([lower], false)).toContain('authorization = "DOCS_API_KEY"');
  });

  it('writes no file at all when every server is unrepresentable', async () => {
    // A file of nothing but apologies is an artifact `check` has to reason about and a
    // user has to wonder about. `doctor` still reports the gap, from the same canonical.
    const list = await servers();
    const renamed: McpServer = {
      ...serverAt(list, 'zebra-stdio'),
      env: { API_KEY: envRef('MY_TOKEN') },
    };
    expect(renderConfigToml([renamed], true)).toBe('');
  });

  it('names the server and never the value', async () => {
    // Unchanged by T083 and still the rule that matters most: a message naming the
    // credential would commit the secret to a different file (T044).
    const list = await servers();
    const renamed: McpServer = {
      ...serverAt(list, 'zebra-stdio'),
      env: { API_KEY: envRef('MY_TOKEN') },
    };
    const reported = unrepresentableServers([renamed, serverAt(list, 'alpha-http')]);

    expect(reported.map((r) => r.id)).toEqual(['zebra-stdio']);
    expect(reported[0]!.hint).toContain('tools:');
    expect(reported[0]!.why).not.toContain('MY_TOKEN=');
  });
});
