import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, describe, expect, it } from 'vitest';

/**
 * T061: the Homebrew tap is one script's output. What it writes is pinned byte for byte, because
 * the release workflow pushes it unreviewed to a repository users install from.
 */

const run = promisify(execFile);
const repoRoot = path.resolve(import.meta.dirname, '../../..');
const script = path.join(repoRoot, 'scripts/stage-homebrew-tap.mjs');
const SHA = 'a'.repeat(64);
const stage = (...args: string[]) => run(process.execPath, [script, ...args]);

const scratch: string[] = [];
afterEach(async () => {
  await Promise.all(scratch.splice(0).map((d) => rm(d, { recursive: true, force: true })));
});
async function tap(): Promise<string> {
  const dir = await mkdtemp(path.join(tmpdir(), 'rulegate-tap-'));
  scratch.push(dir);
  return dir;
}

describe('the Homebrew tap (T061)', () => {
  it('writes a formula that installs the exact npm tarball, pinned by its sha256', async () => {
    const dir = await tap();
    await stage(dir, '1.2.3', SHA);
    expect(await readFile(path.join(dir, 'Formula/rulegate.rb'), 'utf8')).toBe(
      `# Generated by scripts/stage-homebrew-tap.mjs in sayansr26/rulegate on each release.
# Edit that script, not this file: the next release overwrites it.
class Rulegate < Formula
  desc "Sync, verify, and inspect config for AI coding agents"
  homepage "https://github.com/sayansr26/rulegate"
  url "https://registry.npmjs.org/rulegate/-/rulegate-1.2.3.tgz"
  sha256 "${SHA}"
  license "MIT"

  depends_on "node"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink libexec.glob("bin/*")
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/rulegate --version").strip

    system "git", "init", "-q"
    (testpath/"CLAUDE.md").write "# Project\\n\\nUse small modules.\\n"
    system bin/"rulegate", "init", "--yes"
    system bin/"rulegate", "check"
  end
end
`,
    );
    expect(await readFile(path.join(dir, 'README.md'), 'utf8')).toContain(
      'brew install sayansr26/rulegate/rulegate',
    );
  });

  it('keeps `desc` within what `brew audit` accepts', async () => {
    const dir = await tap();
    await stage(dir, '1.2.3', SHA);
    const formula = await readFile(path.join(dir, 'Formula/rulegate.rb'), 'utf8');
    const desc = /^ {2}desc "(.*)"$/m.exec(formula)![1]!;
    expect(desc.length).toBeLessThanOrEqual(80);
    expect(desc).not.toMatch(/^(?:a|an|the)\b/i);
    expect(desc).not.toMatch(/\.$/);
    expect(desc.toLowerCase().startsWith('rulegate')).toBe(false);
  });

  it('reports a stale tap with --check, and writes nothing', async () => {
    const dir = await tap();
    await stage(dir, '1.2.3', SHA);
    await expect(stage(dir, '1.2.3', SHA, '--check')).resolves.toBeDefined();
    await writeFile(path.join(dir, 'README.md'), 'edited\n');
    await expect(stage(dir, '1.2.4', SHA, '--check')).rejects.toMatchObject({ code: 1 });
    expect(await readFile(path.join(dir, 'README.md'), 'utf8')).toBe('edited\n');
  });

  it('refuses a version or checksum it cannot vouch for, as a usage error', async () => {
    const dir = await tap();
    await expect(stage(dir, 'latest', SHA)).rejects.toMatchObject({ code: 2 });
    await expect(stage(dir, '1.2.3', 'abc')).rejects.toMatchObject({ code: 2 });
    await expect(stage(dir)).rejects.toMatchObject({ code: 2 });
  });
});
