import { cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { computePlan, NodeFileSystem } from '@rulegate/core';
import { ADAPTERS } from '../src/registry.js';
import { runSync } from '../src/commands/sync.js';
import { runCheck } from '../src/commands/check.js';
import { ExitCode } from '../src/ui/exit.js';

const fixtures = fileURLToPath(new URL('../../../fixtures/', import.meta.url));

let repo: string;

beforeEach(async () => {
  repo = await mkdtemp(path.join(tmpdir(), 'rulegate-mcp-'));
  // A repository whose only canonical content is MCP servers. No rules at all.
  await cp(path.join(fixtures, 'claude-code-mcp/input'), repo, { recursive: true });
});

afterEach(async () => {
  await rm(repo, { recursive: true, force: true });
});

const read = (rel: string) => readFile(path.join(repo, rel), 'utf8');
const servers = path.join('.rulegate', 'mcp', 'servers.yaml');

/** Not a real credential. Shaped like one so the scan has something to find. */
const FAKE_TOKEN = 'ghp_0123456789abcdefghijklmnopqrstuvwxyz';

describe('rulegate sync — MCP (T038)', () => {
  it('generates every enabled tool’s MCP config from one canonical file', async () => {
    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);

    const claude = JSON.parse(await read('.mcp.json')) as Record<string, unknown>;
    const cursor = JSON.parse(await read('.cursor/mcp.json')) as Record<string, unknown>;

    expect(claude['//']).toContain('generated by rulegate');
    expect(cursor['//']).toContain('generated by rulegate');
    // The same canonical server, spelled the way each tool expands it. One character
    // apart, and the difference is whether the credential arrives.
    expect(await read('.mcp.json')).toContain('"${GITHUB_TOKEN}"');
    expect(await read('.cursor/mcp.json')).toContain('"${env:GITHUB_TOKEN}"');
  });

  it('is clean to `check` immediately after a sync, and stale after an edit', async () => {
    await runSync({ cwd: repo, quiet: true });
    expect(await runCheck({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);

    // A rule edited without a sync is the case `check` exists for; the same holds for a
    // server. Removing one must show up as drift rather than as silence.
    const yaml = await read(servers);
    await writeFile(
      path.join(repo, servers),
      yaml.replace(/ {2}linear-sse:[\s\S]*?\n\n/, ''),
      'utf8',
    );
    expect(await runCheck({ cwd: repo, quiet: true })).toBe(ExitCode.Failure);
  });

  it('removes the MCP artifacts when the last server goes', async () => {
    await runSync({ cwd: repo, quiet: true });
    await rm(path.join(repo, servers));

    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Ok);
    // The T067 guarantee, now covering a second artifact kind: a generated file whose
    // source is gone is removed rather than left on disk for the tool to keep loading.
    await expect(read('.mcp.json')).rejects.toThrow();
    await expect(read('.cursor/mcp.json')).rejects.toThrow();
  });

  it('refuses the whole run rather than writing a literal secret', async () => {
    // Not a real credential — shaped like one so the check has something to find.
    const yaml = await read(servers);
    await writeFile(
      path.join(repo, servers),
      yaml.replace('    timeout: 600000', `    timeout: 600000\n    vendorAuth: ${FAKE_TOKEN}`),
      'utf8',
    );

    expect(await runSync({ cwd: repo, quiet: true })).toBe(ExitCode.Failure);
    // Nothing written, not "written and then complained about".
    await expect(read('.mcp.json')).rejects.toThrow();

    // Defence in depth, and it is real rather than theoretical. `parse()` accumulates
    // instead of throwing, so the offending server still reaches the adapters — and the
    // render scan fires on what each of them actually produced. Three errors from three
    // independent points, and not one of them quotes the value.
    const plan = await computePlan({
      repoRoot: repo,
      fs: new NodeFileSystem(repo),
      adapters: ADAPTERS,
    });
    const messages = plan.errors.filter((e) => e.code === 'E_LITERAL_SECRET').map((e) => e.message);

    expect(messages).toHaveLength(3);
    expect(messages.some((m) => m.includes('.mcp.json'))).toBe(true);
    expect(messages.some((m) => m.includes('.cursor/mcp.json'))).toBe(true);
    expect(messages.join(' ')).not.toContain(FAKE_TOKEN);
  });
});
