import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

const RULES_DOCS: SourceLink = {
  url: 'https://kilo.ai/docs/customize/custom-rules',
  title: 'Kilo Code — Custom rules',
  retrieved: '2026-09-26',
};

const SETTINGS_DOCS: SourceLink = {
  url: 'https://kilo.ai/docs/getting-started/settings',
  title: 'Kilo Code — Settings and config files',
  retrieved: '2026-09-26',
};

const AGENTS_DOCS: SourceLink = {
  url: 'https://kilo.ai/docs/customize/agents-md',
  title: 'Kilo Code — AGENTS.md',
  retrieved: '2026-09-26',
};

/** The legacy loader's own documentation, which the public pages summarize. */
const MIGRATION_SOURCE: SourceLink = {
  url: 'https://github.com/Kilo-Org/kilo/blob/main/packages/opencode/src/kilocode/docs/rules-migration.md',
  title: 'Kilo source — Kilocode rules migration',
  retrieved: '2026-09-26',
};

/**
 * What Kilo actually loads, and in what order.
 *
 * Kilo (VS Code, JetBrains and the CLI share one config; the codebase is an OpenCode fork)
 * sends every source together — `kilo.jsonc` instructions, `AGENTS.md`, and the legacy
 * `.kilocode/` rules the migrator injects into `instructions` — so `'additive'`.
 */
export const docs: AdapterDocs = {
  toolName: 'Kilo Code',
  homepage: 'https://kilo.ai',
  verifiedAgainst: { version: 'Kilo 1.0.25 (source, main branch)', date: '2026-09-26' },
  resolution: 'additive',
  files: [
    {
      pattern: '.kilocode/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      description:
        'The legacy rules directory, auto-loaded for backward compatibility: only the immediate .md children, in directory-listing order. This is what Rulegate generates, because it is the one Kilo path that loads without an entry in a config file.',
      source: RULES_DOCS,
    },
    {
      pattern: '.kilocoderules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'The legacy single-file rules at the project root, still auto-loaded. Rulegate imports it and never writes it.',
      source: MIGRATION_SOURCE,
    },
    {
      pattern: '.kilocoderules-*',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Mode-specific legacy single files (.kilocoderules-code and the like). Like the mode directories, Kilo loads them in every mode. Rulegate imports them as ordinary rules and never writes them.',
      source: MIGRATION_SOURCE,
    },
    {
      pattern: '.kilocode/rules-*/*.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Mode-specific rule directories (code, architect, ask, debug, orchestrator). Kilo loads them in every mode, not only their own. Rulegate imports them as ordinary rules and never writes them.',
      source: MIGRATION_SOURCE,
    },
    {
      pattern: '.kilo/kilo.jsonc',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        "The project config, preferred over a root kilo.jsonc. Its instructions entries are the current way to load rules, including anything in .kilo/rules/, which is not auto-loaded. Kilo's Settings UI writes this file, so Rulegate imports its local instructions and never writes it.",
      source: SETTINGS_DOCS,
    },
    {
      pattern: '.kilo/kilo.json',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        'The JSON spelling of the project config under .kilo/. Imported like .kilo/kilo.jsonc, never written.',
      source: SETTINGS_DOCS,
    },
    {
      pattern: 'kilo.json',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        'The JSON spelling of the root project config, deep-merged with kilo.jsonc. Imported, never written.',
      source: SETTINGS_DOCS,
    },
    {
      pattern: 'kilo.jsonc',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        'The project config at the root, deep-merged with kilo.json and the legacy opencode.json. Imported, never written.',
      source: SETTINGS_DOCS,
    },
    {
      pattern: 'opencode.json',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        "OpenCode's project config, which Kilo still deep-merges. The opencode adapter imports it, so this one does not. Kilo does not read .opencode/, so the opencode adapter's output never reaches Kilo.",
      source: SETTINGS_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Loaded at the root when a task starts (AGENT.md is the fallback spelling); a per-directory copy is loaded when the agent reads a file in that directory. Generated by the codex adapter, not by this one — so enabling kilo and codex together sends Kilo the same rules twice.',
      source: AGENTS_DOCS,
    },
    {
      pattern: '~/.config/kilo/kilo.jsonc',
      scope: 'global',
      role: 'settings',
      managed: false,
      description:
        'The global config. Its instructions load before the project ones, which take precedence. Reported, never written.',
      source: SETTINGS_DOCS,
    },
    {
      pattern: '~/.kilocode/rules/*.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'The legacy global rules directory, still auto-loaded. Outside the repository, so Rulegate reports it and never writes it.',
      source: MIGRATION_SOURCE,
    },
  ],
  limits: {
    note: 'Kilo documents no size cap on rule files or AGENTS.md.',
  },
  notes: [
    {
      level: 'warn',
      message:
        "Rulegate writes .kilocode/rules/, which Kilo documents as legacy and loads only for backward compatibility; its docs recommend moving rules into kilo.jsonc instructions. Rulegate cannot follow that advice without owning kilo.jsonc, which Kilo's own Settings UI edits. If Kilo drops the legacy loader, the generated rules stop loading and nothing reports it.",
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'Kilo loads .kilocode/rules/ in directory-listing order, which it does not sort. Generated files carry a zero-padded position prefix so that a sorted listing matches canonical order; on a filesystem that lists in another order, the rules still all load, possibly in a different sequence.',
      source: MIGRATION_SOURCE,
    },
    {
      level: 'info',
      message:
        "Kilo's pages disagree about CLAUDE.md: the AGENTS.md page names only AGENTS.md and AGENT.md, while the rules-migration notes say CLAUDE.md is loaded natively, as OpenCode does. It is left out of this list until one of them is confirmed.",
      source: AGENTS_DOCS,
    },
    {
      level: 'info',
      message:
        'Import skips remote URLs, home-directory and absolute paths in instructions, and anything under .agent-os/, .ruler/, .rulesync/ or .rulegate/ or at a file another adapter imports (AGENTS.md, .cursor/rules/*.mdc, .github/copilot-instructions.md and the like — matched by the patterns that adapter reads, so .claude/docs/ is still imported), each with a warning. Remote instructions are fetched by Kilo itself; Rulegate never fetches them.',
      source: SETTINGS_DOCS,
    },
  ],
};
