import {
  ADAPTER_API_VERSION,
  RulegateError,
  basenamePosix,
  claimRuleId,
  detected,
  importConcatenated,
  importRuleId,
  importedRule,
  finalizeArtifact,
  isCanonicalSource,
  renderConcatenated,
  selects,
  sortRules,
  withHtmlMarker,
  type Adapter,
  type AdapterContext,
  type Artifact,
  type Canonical,
  type DetectResult,
  type ImportResult,
  slugForId,
  type RuleDocument,
} from '@rulegate/adapter-kit';
import { assertRenderable, frontmatterFor, parseMdc, renderMdcFrontmatter } from './mdc.js';
import { MCP_FILE, importMcpConfig, renderMcpJson } from './mcp.js';
import { docs } from './docs.js';

export const RULES_DIR = '.cursor/rules';
export const LEGACY_FILE = '.cursorrules';

const DETECTION_PATHS = ['.cursor', LEGACY_FILE] as const;

async function detect(ctx: AdapterContext): Promise<DetectResult> {
  const evidence: string[] = [];
  for (const path of DETECTION_PATHS) {
    if (await ctx.fs.exists(path)) evidence.push(path);
  }
  return detected(evidence);
}

/**
 * Both mechanisms are imported, not just the modern one.
 *
 * `.cursorrules` is usually the same rules again in one file, and collapsing that
 * duplication is T018's job — but it is only *usually*, and a repo that stopped
 * maintaining its `.mdc` files has its real content in the legacy file. Dropping a source
 * because it is probably redundant is how an import quietly loses somebody's rules.
 */
async function read(ctx: AdapterContext): Promise<Partial<Canonical>> {
  const rules: RuleDocument[] = [];
  const taken = new Set<string>();

  for (const path of await ctx.fs.glob(`${RULES_DIR}/**/*.mdc`)) {
    if (isCanonicalSource(ctx.canonical.manifest, path)) continue;
    const contents = await ctx.fs.tryReadFile(path);
    if (contents === undefined) continue;

    const parsed = parseMdc(contents);
    if (parsed.body === '' && parsed.description === undefined) continue;

    const base = basenamePosix(path).replace(/\.mdc$/i, '');
    rules.push(
      importedRule({
        id: claimRuleId(importRuleId(base, 'cursor'), taken),
        ...(parsed.description === undefined ? {} : { description: parsed.description }),
        globs: parsed.globs,
        body: parsed.body,
        unknown: parsed.unknown,
        source: { file: path, line: 1 },
      }),
    );
  }

  if (!isCanonicalSource(ctx.canonical.manifest, LEGACY_FILE)) {
    const legacy = await ctx.fs.tryReadFile(LEGACY_FILE);
    if (legacy !== undefined) {
      for (const rule of importConcatenated({
        file: LEGACY_FILE,
        contents: legacy,
        headingLevel: 2,
        idFallback: 'cursorrules',
      })) {
        rules.push({ ...rule, id: claimRuleId(rule.id, taken) });
      }
    }
  }

  return {
    ...(rules.length === 0 ? {} : { rules }),
    ...(await readMcp(ctx)),
  };
}

/**
 * The MCP half, guarded separately from the rules half.
 *
 * A repository can hold `.cursor/mcp.json` and no rules at all, so folding this into the rules
 * return would import no servers there — the mirror of the bug T038 found on the write
 * side, where one early return covered the whole adapter.
 */
async function readMcp(ctx: AdapterContext): Promise<ImportResult> {
  if (isCanonicalSource(ctx.canonical.manifest, MCP_FILE)) return {};
  const contents = await ctx.fs.tryReadFile(MCP_FILE);
  if (contents === undefined) return {};
  const { servers, warnings } = importMcpConfig(contents);
  return {
    ...(servers.length === 0 ? {} : { mcpServers: servers }),
    ...(warnings.length === 0 ? {} : { warnings }),
  };
}

function mdcPath(rule: RuleDocument): string {
  return `${RULES_DIR}/${slugForId(rule.id)}.mdc`;
}

function renderMdc(rule: RuleDocument, marker: boolean): string {
  assertRenderable(rule);
  // The marker follows the frontmatter rather than leading the file: .mdc frontmatter
  // must occupy the first bytes, so a leading comment would break parsing.
  const head = renderMdcFrontmatter(frontmatterFor(rule));
  const body = rule.body.replace(/\n+$/, '');
  return marker
    ? `${head}\n<!-- generated by rulegate; edit .rulegate/ instead -->\n\n${body}`
    : `${head}\n${body}`;
}

async function write(ctx: AdapterContext): Promise<readonly Artifact[]> {
  const { canonical } = ctx;
  const marker = canonical.manifest.options.marker;
  const rules = sortRules(canonical.rules.filter((r) => selects(r.frontmatter.tools, 'cursor')));

  const artifacts: Artifact[] = [];
  const claimed = new Map<string, string>();

  for (const rule of rules) {
    const path = mdcPath(rule);

    const previous = claimed.get(path);
    if (previous !== undefined) {
      // Two rule ids slugging to one filename would silently drop one rule's content.
      throw new RulegateError({
        code: 'E_ARTIFACT_PATH_CONFLICT',
        message: `rules \`${previous}\` and \`${rule.id}\` both generate ${path}`,
        source: rule.source,
        hint: 'rename one of the rules so their generated filenames differ',
      });
    }
    claimed.set(path, rule.id);

    if (isCanonicalSource(canonical.manifest, path)) continue;

    artifacts.push(
      finalizeArtifact({
        path,
        contents: renderMdc(rule, marker),
        adapter: 'cursor',
        kind: 'rules',
        provenance: { ruleIds: [rule.id] },
      }),
    );
  }

  // The legacy single file is opt-in. Writing a deprecated file nobody asked for is
  // exactly the kind of first-run surprise that costs trust.
  //
  // `rules.length > 0` used to be an early return covering the whole function; it moved
  // here when MCP made "no rules" stop meaning "no output". Without it, a repository with
  // servers and no rules and `legacy: true` would gain an empty `.cursorrules`.
  if (
    rules.length > 0 &&
    ctx.options['legacy'] === true &&
    !isCanonicalSource(canonical.manifest, LEGACY_FILE)
  ) {
    artifacts.push(
      finalizeArtifact({
        path: LEGACY_FILE,
        contents: withHtmlMarker(
          renderConcatenated(rules, { headingLevel: 2, showGlobs: true }),
          marker,
        ),
        adapter: 'cursor',
        kind: 'rules',
        provenance: { ruleIds: rules.map((r) => r.id) },
      }),
    );
  }

  // MCP is independent of rules: a repository with servers and no rules still has a
  // `.cursor/mcp.json` to generate, which is why the rules branch above no longer returns
  // early for the whole adapter. No `provenance` — no canonical rule contributed to it.
  const mcp = renderMcpJson(canonical.mcpServers, marker);
  if (mcp !== '' && !isCanonicalSource(canonical.manifest, MCP_FILE)) {
    artifacts.push(
      finalizeArtifact({
        path: MCP_FILE,
        contents: mcp,
        adapter: 'cursor',
        kind: 'mcp',
      }),
    );
  }

  return Promise.resolve(artifacts);
}

export const cursor: Adapter = {
  name: 'cursor',
  apiVersion: ADAPTER_API_VERSION,
  detect,
  read,
  write,
  docs,
};

export default cursor;
export { docs, renderMdcFrontmatter, frontmatterFor, MCP_FILE, renderMcpJson };
