#!/usr/bin/env node
/**
 * Generate `docs/tools/<tool>.md` — one precedence page per registered adapter — and
 * `docs/adapters.md`, the adapter registry, from `AdapterDocs`.
 *
 * **Generated, not hand-written, and that is the point.** These pages are the most durable
 * expression of the project's moat: every developer googling "which file does Cursor read"
 * should land on one. Hand-maintained they would begin diverging from `docs.ts` the day
 * after they were written, which is how every precedence table on the internet rots. T025's
 * completion notes deferred them here and said exactly that.
 *
 * Lives at the repo root for the same reason `update-fixtures.mjs` does:
 * `packages/core/test/invariants.test.ts` allows filesystem writes only in `core/src/io/`,
 * `pipeline/apply.ts` and `fs/types.ts`, and it scans `packages/`. A writer inside a
 * published package would mean widening a P0 invariant for a dev script.
 *
 * Deliberately **not** routed through the `sync` pipeline: rendering pages *about* adapters
 * is adapter-shaped knowledge, and `packages/core` carries no tool-specific logic.
 *
 * Usage: pnpm build && node scripts/generate-docs.mjs [--yes|--check]
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repoRoot = fileURLToPath(new URL('../', import.meta.url));

/**
 * A dynamic `import()` of a plain absolute path throws on Windows: `C:\\...` reads as an
 * unknown URL scheme. The built `dist/` has to be addressed as a `file://` URL, which is
 * why the whole Windows matrix reported this script as "build first" on a runner that had
 * just built successfully.
 */
const distUrl = (rel) => pathToFileURL(path.join(repoRoot, rel)).href;

const toolsDir = path.join(repoRoot, 'docs/tools');
const registryPage = path.join(repoRoot, 'docs/adapters.md');

const args = process.argv.slice(2);
const apply = args.includes('--yes');
const check = args.includes('--check');

// `--check` is safe in CI and is the point of having it; `--yes` never is. A docs page
// silently regenerated by the job that is supposed to be verifying it would turn the gate
// into decoration — the `update-fixtures.mjs` reasoning, narrowed to the writing half.
if (apply && process.env['CI'] !== undefined && process.env['CI'] !== '') {
  console.error('generate-docs --yes must never run in CI; use --check there.');
  process.exit(2);
}

const { ADAPTERS } = await import(distUrl('packages/cli/dist/registry.js')).catch((cause) => {
  // Naming the cause matters: this message blamed a missing build for a Windows
  // ESM-scheme failure on a runner that had just built, which cost a full matrix run.
  console.error(
    `build first: pnpm build && node scripts/generate-docs.mjs\n  (import failed: ${cause.message})`,
  );
  process.exit(2);
});

const MARKER =
  '<!-- generated by scripts/generate-docs.mjs; edit packages/adapters/*/src/docs.ts -->';

const SCOPE_LABEL = { project: 'project', nested: 'nested', global: 'user-level' };

const RESOLUTION_PROSE = {
  override:
    'Every file below that is present is **sent to the model**; when two of them conflict, the one nearer the top wins. A file that loses a conflict still costs its tokens.',
  additive:
    'Every file below that is present is **sent to the model**, all together. The order ranks specificity rather than authority — nothing here overrides anything else.',
  'first-match':
    'This tool reads the **first** file below that exists and stops. Everything under it is never opened: it costs nothing and contributes nothing, however carefully it was written.',
};

function escapeCell(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();
}

function sourceLine(source) {
  return `[${escapeCell(source.title)}](${source.url}) — retrieved ${source.retrieved}`;
}

function renderToolPage(adapter) {
  const { docs, name } = adapter;
  const resolution = docs.resolution ?? 'override';
  const out = [];

  out.push(MARKER, '');
  // The H1 is the query it should answer, verbatim. These pages exist to be found.
  out.push(`# Which files does ${docs.toolName} read?`, '');
  out.push(
    `Rulegate adapter id: \`${name}\` · Verified against ${escapeCell(docs.verifiedAgainst.version)} on ${docs.verifiedAgainst.date} · [Homepage](${docs.homepage})`,
    '',
  );
  out.push(RESOLUTION_PROSE[resolution] ?? RESOLUTION_PROSE.override, '');

  out.push('## Precedence', '');
  out.push('| # | Path | Scope | Role | Rulegate writes it | Nesting |');
  out.push('|---|---|---|---|---|---|');
  docs.files.forEach((entry, i) => {
    out.push(
      `| ${String(i + 1)} | \`${escapeCell(entry.pattern)}\` | ${SCOPE_LABEL[entry.scope] ?? entry.scope} | ${entry.role} | ${entry.managed ? 'yes' : 'no'} | ${entry.nesting ?? 'root only'} |`,
    );
  });
  out.push('');

  out.push('## What each file is', '');
  for (const entry of docs.files) {
    out.push(`### \`${entry.pattern}\``, '');
    out.push(entry.description, '');
    out.push(`Source: ${sourceLine(entry.source)}`, '');
  }

  out.push('## Size limits', '');
  if (docs.limits?.maxBytesPerFile !== undefined) {
    out.push(`- Per file: ${String(docs.limits.maxBytesPerFile)} bytes`, '');
  }
  if (docs.limits?.maxTotalBytes !== undefined) {
    out.push(`- Total: ${String(docs.limits.maxTotalBytes)} bytes`, '');
  }
  out.push(docs.limits?.note ?? 'No cap is recorded for this tool.', '');

  // Skills (T052): where this tool reads project skills, which decides where `sync` puts them.
  if (docs.skills !== undefined) {
    out.push('## Skills', '');
    out.push(
      `Reads project skills from ${docs.skills.dirs.map((d) => `\`${d}/\``).join(', ')}, preferred first.`,
      '',
    );
    out.push(
      docs.skills.extensions.length === 0
        ? 'Reads only the Agent Skills frontmatter fields.'
        : `Frontmatter it reads beyond the Agent Skills fields: ${docs.skills.extensions.map((k) => `\`${k}\``).join(', ')}.`,
      '',
    );
    out.push(`Source: ${sourceLine(docs.skills.source)}`, '');
  }

  if ((docs.notes ?? []).length > 0) {
    out.push('## Notes', '');
    for (const note of docs.notes ?? []) {
      out.push(`- **${note.level}** — ${note.message}`);
      if (note.source !== undefined) out.push(`  Source: ${sourceLine(note.source)}`);
    }
    out.push('');
  }

  out.push('## Sources', '');
  const seen = new Map();
  for (const entry of docs.files) seen.set(entry.source.url, entry.source);
  for (const note of docs.notes ?? []) {
    if (note.source !== undefined) seen.set(note.source.url, note.source);
  }
  if (docs.skills !== undefined) seen.set(docs.skills.source.url, docs.skills.source);
  for (const source of [...seen.values()].sort((a, b) => (a.url < b.url ? -1 : 1))) {
    out.push(`- ${sourceLine(source)}`);
  }
  out.push('');

  return out.join('\n');
}

/** Coverage is derived from the roles this adapter actually declares as managed. */
function coverageOf(adapter) {
  const roles = new Set(adapter.docs.files.filter((f) => f.managed).map((f) => f.role));
  const parts = [];
  if (roles.has('instructions')) parts.push('rules');
  if (roles.has('mcp')) parts.push('MCP');
  if (roles.has('skills') || adapter.docs.skills !== undefined) parts.push('skills');
  return parts.length === 0 ? '—' : parts.join(', ');
}

function renderRegistry(adapters) {
  const out = [];
  out.push(MARKER, '');
  out.push('# Adapters', '');
  out.push(
    `Rulegate ships ${String(adapters.length)} adapters. Each one is a pure module — it reads, it returns values, and it never writes to disk or touches the network. See [writing an adapter](writing-an-adapter.md).`,
    '',
  );
  out.push('| Tool | Id | Coverage | Status | Maintainer | Verified against | Precedence |');
  out.push('|---|---|---|---|---|---|---|');
  for (const adapter of adapters) {
    const d = adapter.docs;
    out.push(
      `| ${escapeCell(d.toolName)} | \`${adapter.name}\` | ${coverageOf(adapter)} | ${d.status ?? 'not stated'} | ${escapeCell(d.maintainer ?? 'Rulegate maintainers')} | ${escapeCell(d.verifiedAgainst.version)} (${d.verifiedAgainst.date}) | [which files it reads](tools/${adapter.name}.md) |`,
    );
  }
  out.push('');
  out.push(
    'Coverage is read from each adapter’s own `docs.files`: a row says `MCP` exactly when that adapter declares a managed file with `role: "mcp"`. Nothing here is hand-maintained.',
    '',
    '`Status` is stated by an adapter, never derived from how old its `verifiedAgainst` date is — a page that changed with the calendar would be a CI gate that flaps. `not stated` means exactly that, and is not a synonym for `stable`.',
    '',
  );
  return out.join('\n');
}

function renderIndex(adapters) {
  const out = [MARKER, '', '# Which files does your AI coding tool read?', ''];
  out.push(
    'One page per tool Rulegate supports, generated from the precedence data each adapter carries. Every claim links to the vendor page it came from and the date that page was read.',
    '',
  );
  for (const adapter of adapters) {
    out.push(
      `- [${escapeCell(adapter.docs.toolName)}](${adapter.name}.md) — verified against ${escapeCell(adapter.docs.verifiedAgainst.version)} on ${adapter.docs.verifiedAgainst.date}`,
    );
  }
  out.push('');
  return out.join('\n');
}

const sorted = [...ADAPTERS].sort((a, b) => (a.name < b.name ? -1 : 1));

const planned = new Map();
for (const adapter of sorted) {
  planned.set(path.join(toolsDir, `${adapter.name}.md`), renderToolPage(adapter));
}
planned.set(path.join(toolsDir, 'README.md'), renderIndex(sorted));
planned.set(registryPage, renderRegistry(sorted));

const changes = [];
for (const [file, contents] of planned) {
  const existing = await readFile(file, 'utf8').catch(() => undefined);
  if (existing === contents) continue;
  changes.push({ file, contents, kind: existing === undefined ? 'create' : 'update' });
}

// A page for an adapter that no longer exists is exactly as stale as a missing one, and
// only this script can know which is which.
const present = await readdir(toolsDir).catch(() => []);
for (const entry of present) {
  const file = path.join(toolsDir, entry);
  if (!planned.has(file)) changes.push({ file, contents: undefined, kind: 'delete' });
}

const rel = (file) => path.relative(repoRoot, file);

if (check) {
  if (changes.length === 0) {
    console.log('docs/tools and docs/adapters.md are up to date');
    process.exit(0);
  }
  for (const change of changes) console.error(`${change.kind}  ${rel(change.file)}`);
  console.error(
    `\n${String(changes.length)} generated docs page(s) are stale. run: pnpm build && node scripts/generate-docs.mjs --yes`,
  );
  process.exit(1);
}

if (changes.length === 0) {
  console.log('docs/tools and docs/adapters.md are up to date');
  process.exit(0);
}

for (const change of changes) console.log(`${change.kind}  ${rel(change.file)}`);

if (!apply) {
  console.log(
    `\n${String(changes.length)} change(s); nothing was written. re-run with --yes to apply.`,
  );
  process.exit(0);
}

await mkdir(toolsDir, { recursive: true });
for (const change of changes) {
  if (change.kind === 'delete') {
    const { rm } = await import('node:fs/promises');
    await rm(change.file);
    continue;
  }
  await writeFile(change.file, change.contents, 'utf8');
}
console.log(`\nwrote ${String(changes.length)} file(s).`);
