import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

/**
 * The vendor page, and the URL that was actually read.
 *
 * `docs.windsurf.com/windsurf/cascade/memories` — the URL Windsurf's own documentation
 * links — **307-redirects** to `docs.devin.ai`. The redirect target is recorded here
 * because the URL a reader is sent to is part of the claim: a reviewer following the
 * original lands somewhere else, and a page that moved is a page whose content may have
 * moved with it.
 */
const RULES_DOCS: SourceLink = {
  url: 'https://docs.devin.ai/desktop/cascade/memories',
  title: 'Windsurf — Rules and memories (Cascade)',
  retrieved: '2026-09-04',
};

/**
 * What Windsurf actually loads, and in what order.
 *
 * Ordered highest-precedence first. `.devin/rules/` leads because the vendor states it
 * takes precedence over `.windsurf/rules/`, with the latter kept for backward
 * compatibility — so in a repository that has both, **Rulegate's output is shadowed** and
 * `doctor` has to be able to say so.
 */
export const docs: AdapterDocs = {
  toolName: 'Windsurf',
  homepage: 'https://windsurf.com',
  // Not a release number: the vendor page carries none, and inventing one would be the
  // kind of plausible-looking claim the `1970-01-01` placeholders exist to prevent.
  verifiedAgainst: { version: 'Cascade docs as published 2026-09-04', date: '2026-09-04' },
  // Every applicable rule file is applied; ordering ranks specificity, not authority.
  resolution: 'additive',
  files: [
    {
      pattern: '.devin/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Devin Desktop workspace rules. Documented as taking precedence over .windsurf/rules. Rulegate reads these on import so a Devin user does not lose them, and never writes them: the directory belongs to a different product.',
      source: RULES_DOCS,
    },
    {
      pattern: '.windsurf/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      nesting: 'all-merged',
      description:
        'Workspace rules, one file per rule, each with a trigger: frontmatter key. Discovered in subdirectories and in parent directories up to the git root. This is what Rulegate generates.',
      source: RULES_DOCS,
    },
    {
      pattern: '.windsurfrules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Legacy single-file rules at the workspace root, superseded by .windsurf/rules. Rulegate imports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Read at the workspace root, without frontmatter. Generated by the codex adapter, not by this one — so enabling windsurf and codex together sends Windsurf the same rules twice.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.codeium/windsurf/memories/global_rules.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules, always applied, no frontmatter. Outside the repository, so Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
  ],
  limits: {
    // The vendor states 12,000 CHARACTERS per workspace file and 6,000 for the global one.
    // `maxBytesPerFile` is measured in bytes, and for non-ASCII rules bytes exceed
    // characters — so this can warn on a file that is legally under the cap. Declared
    // anyway with the mismatch stated: a cap nobody recorded and a cap that is slightly
    // conservative are not the same thing, and only the second can be corrected.
    maxBytesPerFile: 12000,
    note: 'Windsurf documents 12,000 characters per workspace rule file and 6,000 for the global one. Rulegate measures bytes, so a rule using non-ASCII characters may be reported over the limit while still being under it.',
  },
  notes: [
    {
      level: 'warn',
      message:
        'Multiple glob patterns are undocumented. The vendor shows a single bare pattern (globs: **/*.test.ts) and does not say how several are separated; Rulegate joins them with commas, matching Cursor .mdc and community practice. A rule whose scoping matters and that carries more than one pattern is worth checking in Windsurf before relying on it.',
      source: RULES_DOCS,
    },
    {
      level: 'warn',
      message:
        '.devin/rules takes precedence over .windsurf/rules. In a repository that has both, the files Rulegate generates are shadowed by a directory it deliberately does not write.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'trigger: is derived, not authored. A rule with globs becomes trigger: glob and a repo-wide rule becomes trigger: always_on; model_decision and manual are never generated, because both let the model skip a rule the author asked for.',
      source: RULES_DOCS,
    },
  ],
  // `.devin/skills/` is preferred and `.windsurf/skills/` is legacy. `.claude/skills/` is read only when a setting enables it, so it is not counted on.
  skills: {
    dirs: ['.devin/skills', '.windsurf/skills', '.agents/skills'],
    extensions: [],
    source: {
      url: 'https://docs.devin.ai/desktop/cascade/skills',
      title: 'Windsurf — Cascade skills',
      retrieved: '2026-09-29',
    },
  },
  // Workflows. `.devin/workflows/` is preferred by the vendor and never written, like `.devin/rules/`; `.windsurf/workflows/` is still read. No frontmatter or argument syntax is documented, and a workflow is capped at 12 000 characters.
  commands: {
    dir: '.windsurf/workflows',
    extension: '.md',
    format: 'markdown-plain',
    extensions: [],
    maxChars: 12000,
    source: {
      url: 'https://docs.devin.ai/desktop/cascade/workflows',
      title: 'Windsurf — Cascade workflows',
      retrieved: '2026-09-29',
    },
  },
};
