import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

const RULES_DOCS: SourceLink = {
  url: 'https://docs.cline.bot/features/cline-rules',
  title: 'Cline — Cline Rules',
  retrieved: '2026-09-04',
};

/**
 * What Cline actually loads.
 *
 * **This is the roster's clearest duplicate-load case, and it is the reason to have this
 * adapter's `docs` right.** Cline reads `.cursorrules`, `.windsurfrules` and `AGENTS.md` on
 * top of its own directory — three files that *other* Rulegate adapters generate. Enabling
 * `cline` alongside `codex` sends Cline the same canonical rules twice, and alongside
 * `cursor` and `windsurf` as well, four times. Every one of those is declared here with
 * `managed: false`, which is what lets `doctor`'s `duplicateLoadWarnings` fire from adapter
 * data with no Cline-specific code anywhere in the codebase (T073).
 *
 * **The order below is not a ranking the vendor publishes.** `AdapterDocs.files` is an
 * ordered field, so listing them at all asserts something — the vendor documents a rank only
 * between workspace and global rules, and says nothing about how the four workspace formats
 * rank against each other. `.clinerules/*` leads because it is the tool's own mechanism, and
 * each cross-tool entry says in its description that no rank is documented.
 */
export const docs: AdapterDocs = {
  toolName: 'Cline',
  homepage: 'https://cline.bot',
  // The rules page carries no version number, so the documentation date is the honest
  // stamp. Gemini's entry uses the same form for the same reason.
  verifiedAgainst: { version: 'Cline docs as published 2026-09-04', date: '2026-09-04' },
  // Every detected rule file is combined; the panel lets a user toggle them individually.
  resolution: 'additive',
  files: [
    {
      pattern: '.clinerules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      description:
        'Workspace rules. Cline processes all .md and .txt files inside .clinerules/ and combines them. This is what Rulegate generates; it writes .md only, and imports both extensions.',
      source: RULES_DOCS,
    },
    {
      pattern: '.cursorrules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Cline reads Cursor’s legacy rules file as well as its own. Generated by the cursor adapter when options.legacy is set, not by this one. The vendor documents no rank among the workspace formats.',
      source: RULES_DOCS,
    },
    {
      pattern: '.windsurfrules',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Cline reads Windsurf’s legacy rules file as well as its own. Rulegate never writes it. The vendor documents no rank among the workspace formats.',
      source: RULES_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      description:
        'Cline reads AGENTS.md as well as its own directory. Generated by the codex adapter, so enabling cline and codex together sends Cline the same rules twice. The vendor documents no rank among the workspace formats.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/Documents/Cline/Rules',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules, combined with workspace rules. Workspace rules take precedence when the two conflict — the one ranking the vendor does document. Outside the repository, so Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
  ],
  // No cap is published. Said explicitly, because "no limit" and "nobody checked" must not
  // look the same in `doctor`'s output.
  limits: { note: 'Cline publishes no size cap for rule files.' },
  notes: [
    {
      level: 'warn',
      message:
        'Cline reads .cursorrules, .windsurfrules and AGENTS.md in addition to .clinerules/. These are additive, not an override chain, so enabling cline alongside codex, cursor or windsurf sends Cline the same canonical rules more than once. `rulegate doctor` counts the cost per repository (W_DUPLICATE_LOAD); this note records why it happens.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'The vendor documents no precedence among the four workspace formats — only that workspace rules beat global ones. The order in this file leads with Cline’s own directory and asserts nothing further.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'Cline has no project-level MCP configuration file: MCP servers live in user-level storage, outside any repository. This adapter therefore generates no MCP artifact.',
      source: RULES_DOCS,
    },
  ],
};
