import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

const RULES_DOCS: SourceLink = {
  url: 'https://antigravity.google/docs/rules',
  title: 'Google Antigravity — Rules configuration reference',
  retrieved: '2026-09-26',
};

/**
 * What Antigravity actually loads, and in what order.
 *
 * Rules are cumulative across every scope, with a more specific directory winning a
 * conflict — so `'additive'`, and the order below ranks specificity. The rules page now
 * documents the on-disk syntax, which makes agent-os's "set the glob in the UI" workaround
 * (its notes date from 2026-09-15) obsolete.
 */
export const docs: AdapterDocs = {
  toolName: 'Antigravity',
  homepage: 'https://antigravity.google',
  // Not a release number: the page carries none, and the tool was not run for this.
  verifiedAgainst: { version: 'Rules docs as published 2026-09-26', date: '2026-09-26' },
  resolution: 'additive',
  files: [
    {
      pattern: '.agents/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      nesting: 'all-merged',
      description:
        'Workspace rules, one file per rule, each opening with YAML frontmatter that declares a trigger. Only the immediate .md children are scanned; a file with missing frontmatter or an unrecognized trigger is silently discarded. This is what Rulegate generates.',
      source: RULES_DOCS,
    },
    {
      pattern: '.agent/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'The legacy name of the rules directory, still read. Rulegate imports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '.agents/AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Antigravity-specific instructions without frontmatter, beside the rules directory. Rulegate imports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '.agents/GEMINI.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'The GEMINI.md spelling of the same Antigravity-specific file. Rulegate imports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Read in any directory, without frontmatter. Generated by the codex adapter, not by this one — so enabling antigravity and codex together sends Antigravity the same rules twice.',
      source: RULES_DOCS,
    },
    {
      pattern: 'GEMINI.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Read in any directory, without frontmatter. Generated by the gemini adapter, not by this one — so enabling antigravity and gemini together sends Antigravity the same rules twice.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.gemini/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules. Outside the repository, so Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.gemini/GEMINI.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules; the same file Gemini CLI reads, so it reaches both tools. Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.gemini/config/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules in the config directory. Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.gemini/config/rules/*.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rule files with the same frontmatter as .agents/rules. Rulegate reports them and never writes them.',
      source: RULES_DOCS,
    },
  ],
  limits: {
    maxBytesPerFile: 24000,
    note: 'Antigravity documents 24,000 bytes per rule file, and a 20,000-token budget shared by every global and always_on rule together. Rulegate checks the per-file cap; the shared budget spans files it does not write, so it is reported here rather than enforced.',
  },
  notes: [
    {
      level: 'info',
      message:
        'trigger: is derived, not authored. A rule with globs becomes trigger: glob and a repo-wide rule becomes trigger: always_on; model_decision and manual are never generated, because both let the model skip a rule the author asked for. Imported rules in either mode come back as ordinary rules, with a warning.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'globs: is always double-quoted and comma-separated, as the vendor example writes it ("*.proto, **/*.pb.go"). Bare, a pattern starting with * is a YAML alias, and a block that fails to parse gets the rule discarded without an error. Import imports such a file with a warning that it is not in effect today, and the render quotes it.',
      source: RULES_DOCS,
    },
    {
      level: 'warn',
      message:
        'Antigravity also reads AGENTS.md and GEMINI.md in every directory. With codex or gemini enabled as well, the same rules reach Antigravity from two or three files and are billed each time.',
      source: RULES_DOCS,
    },
  ],
};
