import type { AdapterDocs, PrecedenceEntry, SourceLink } from '@rulegate/adapter-kit';

const INSTRUCTIONS_DOCS: SourceLink = {
  url: 'https://zed.dev/docs/ai/instructions',
  title: 'Zed — Agent Instructions',
  retrieved: '2026-09-04',
};

/**
 * One link in Zed's chain.
 *
 * Every entry but `.rules` is `managed: false` and owned by some *other* adapter — which is
 * exactly what makes this file interesting: `doctor` cross-references `managed` across
 * adapters, so it will print `from cursor` and `from codex` beside these rows without a
 * line of Zed-specific code anywhere.
 */
function link(pattern: string, description: string): PrecedenceEntry {
  return {
    pattern,
    scope: 'project',
    role: 'instructions',
    managed: false,
    description,
    source: INSTRUCTIONS_DOCS,
  };
}

/**
 * What Zed actually loads — and it is the roster's only true first-match chain.
 *
 * Zed checks nine filenames in order and **uses the first that exists, full stop**. The
 * other eight are never opened. Five of the nine are files other Rulegate adapters
 * generate, so a repository with `.cursorrules` and a generated `CLAUDE.md` sends Zed the
 * `.cursorrules` and ignores the `CLAUDE.md` entirely — a fact no other tool in the roster
 * produces, and precisely the question `rulegate doctor` exists to answer.
 *
 * `resolution: 'first-match'` is what encodes that, and it had to be added to the frozen
 * kit for this adapter (T045a). `'override'` — which the seeded issue prescribed — gets the
 * *shadowing* right and the *loading* wrong: under it `doctor` counts all nine as loaded,
 * because for Claude Code a shadowed file genuinely is still sent and still costs tokens.
 * Here it is not sent at all, and reporting otherwise would bill the user for eight files
 * Zed never reads.
 */
export const docs: AdapterDocs = {
  toolName: 'Zed',
  homepage: 'https://zed.dev',
  // The instructions page carries no version number; the documentation date is the honest
  // stamp, and `verifiedAgainst.version` must not be a plausible-looking guess.
  verifiedAgainst: { version: 'Zed docs as published 2026-09-04', date: '2026-09-04' },
  resolution: 'first-match',
  files: [
    {
      pattern: '.rules',
      scope: 'project',
      role: 'instructions',
      managed: true,
      description:
        'First in Zed’s list, so it wins whenever it exists. This is what Rulegate generates: writing it is what makes the other eight irrelevant, rather than leaving the answer to whichever file happens to be present.',
      source: INSTRUCTIONS_DOCS,
    },
    link(
      '.cursorrules',
      'Second. Read only when .rules is absent. Generated by the cursor adapter under options.legacy.',
    ),
    link('.windsurfrules', 'Third. Read only when the two above are absent.'),
    link(
      '.clinerules',
      'Fourth. Note this is the legacy single *file*; the cline adapter generates the .clinerules/ directory.',
    ),
    link(
      '.github/copilot-instructions.md',
      'Fifth. Generated by the copilot adapter, and read here only when the four above are absent.',
    ),
    link('AGENT.md', 'Sixth. Singular, and distinct from AGENTS.md below. No adapter writes it.'),
    link(
      'AGENTS.md',
      'Seventh. Generated by the codex adapter, and read only when the six above are absent.',
    ),
    link(
      'CLAUDE.md',
      'Eighth. Generated by the claude-code adapter, and read only when the seven above are absent.',
    ),
    link(
      'GEMINI.md',
      'Ninth and last. Generated by the gemini adapter, and read only when every file above is absent.',
    ),
    {
      pattern: '~/.config/zed/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'Personal instructions, applied alongside the project file rather than competing with it — project instructions override it when they conflict. Outside the repository, so Rulegate reports it and never writes it.',
      source: INSTRUCTIONS_DOCS,
    },
  ],
  limits: { note: 'Zed publishes no size cap for instruction files.' },
  notes: [
    {
      level: 'warn',
      message:
        'Zed reads the FIRST of .rules, .cursorrules, .windsurfrules, .clinerules, .github/copilot-instructions.md, AGENT.md, AGENTS.md, CLAUDE.md, GEMINI.md — and no others. Five of those are files other Rulegate adapters generate, so in a repository that has several, everything below the first is invisible to Zed however carefully it was written.',
      source: INSTRUCTIONS_DOCS,
    },
    {
      level: 'info',
      message:
        'Whether Zed searches subdirectories or only the worktree root is undocumented, and multi-worktree behaviour is not described either. No entry here declares `nesting`, so doctor reports the worktree root only rather than claiming a walk that may not happen.',
      source: INSTRUCTIONS_DOCS,
    },
  ],
};
