import type { ScaffoldFile } from '@rulegate/core';
import { toolNames, type ToolNames } from './names.js';
import { readVersion } from '../../version.js';

/**
 * Every file `rulegate adapter new <tool>` creates.
 *
 * The templates live in the CLI rather than in core or the kit because they encode this
 * monorepo's layout — package directories, fixture paths, the registry — which is not
 * something a published library should know. Core only writes the bytes (`applyScaffold`).
 *
 * The stub is a *working* concatenated-Markdown adapter rather than an empty one. Three
 * of the five shipped adapters have that shape, `pnpm test` is green the moment the
 * scaffold lands, and what is left for the contributor is the part only they can supply:
 * the real file path, the real precedence rules, and a hand-written golden.
 */
export function scaffoldFiles(id: string): readonly ScaffoldFile[] {
  const n = toolNames(id);
  return [
    file(`packages/adapters/${n.id}/package.json`, packageJson(n)),
    file(`packages/adapters/${n.id}/tsconfig.json`, tsconfig()),
    file(`packages/adapters/${n.id}/src/index.ts`, adapterSource(n)),
    file(`packages/adapters/${n.id}/src/docs.ts`, adapterDocs(n)),
    file(`packages/adapters/${n.id}/test/detect.test.ts`, detectTest(n)),
    file(`packages/adapters/${n.id}/test/write.test.ts`, writeTest(n)),
    file(`packages/adapters/${n.id}/test/read.test.ts`, readTest(n)),

    file(`fixtures/${n.id}/input/.rulegate/rulegate.yaml`, manifestFixture(n)),
    file(`fixtures/${n.id}/input/.rulegate/rules/10-style.md`, STYLE_RULE),
    file(`fixtures/${n.id}/input/.rulegate/rules/20-testing.md`, TESTING_RULE),
    file(`fixtures/${n.id}/input/.rulegate/rules/30-cursor-only.md`, cursorOnlyRule(n)),
    file(`fixtures/${n.id}/expected/${n.artifact}`, expectedArtifact()),

    file(`fixtures/${n.id}-detect/positive/${n.artifact}`, DETECT_POSITIVE),
    file(`fixtures/${n.id}-detect/positive/${n.dotDir}/config.json`, '{}\n'),
    file(`fixtures/${n.id}-detect/negative/README.md`, '# Some project\n'),

    file(`fixtures/${n.id}-import/input/${n.artifact}`, importInput()),
    file(`fixtures/${n.id}-import/expected/rules/style.md`, IMPORT_EXPECTED),
  ];
}

function file(path: string, contents: string): ScaffoldFile {
  return { path, contents, kind: 'create' };
}

/** The two rules the write fixture renders, and the one it must exclude. */
const STYLE_RULE = `---
description: Style
order: 10
---

Prefer small modules.
`;

const TESTING_RULE = `---
description: Testing
order: 20
---

Colocate tests beside the code they cover.
`;

function cursorOnlyRule(n: ToolNames): string {
  return `---
description: Cursor only
tools: [cursor]
order: 30
---

This rule must not reach ${n.id}.
`;
}

function manifestFixture(n: ToolNames): string {
  return `schemaVersion: 1\ntools:\n  - ${n.id}\n  - cursor\n`;
}

/**
 * The golden, as this stub renders it.
 *
 * It is generated output, which proves only that the adapter agrees with itself — so the
 * scaffold says so, here and in the command's next steps. Replace it with the bytes the
 * tool's documentation says it reads *before* changing `write()`; that is the whole point
 * of a fixture (`fixtures/README.md`).
 */
function expectedArtifact(): string {
  return `<!-- generated by rulegate; edit .rulegate/ instead -->

## Style

Prefer small modules.

## Testing

Colocate tests beside the code they cover.
`;
}

const DETECT_POSITIVE = `# Project context

Prefer small modules.
`;

function importInput(): string {
  return `<!-- generated by rulegate; edit .rulegate/ instead -->

## Style

Prefer small modules.
`;
}

const IMPORT_EXPECTED = `---
description: Style
---

Prefer small modules.
`;

/**
 * Written as literal text rather than `JSON.stringify`, because these files are
 * Prettier's: its array formatting and the serializer's disagree, and a scaffold whose
 * output fails `pnpm format` on the first run is a scaffold that taught the contributor
 * the repository is broken.
 */
function packageJson(n: ToolNames): string {
  // Read from the CLI's own manifest rather than written as a literal. Every package in this
  // workspace releases at one version, so a hardcoded one is correct until the next release
  // and then silently wrong: a scaffolded adapter would be a version island, and
  // `pnpm publish -r` would put it on the registry under a number nothing else shares.
  return `{
  "name": "${n.packageName}",
  "version": "${readVersion()}",
  "description": "Rulegate adapter for ${n.id}.",
  "type": "module",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/sayansr26/rulegate.git",
    "directory": "packages/adapters/${n.id}"
  },
  "homepage": "https://github.com/sayansr26/rulegate#readme",
  "bugs": "https://github.com/sayansr26/rulegate/issues",
  "publishConfig": {
    "access": "public"
  },
  "engines": {
    "node": ">=20"
  },
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  },
  "types": "./dist/index.d.ts",
  "files": [
    "dist"
  ],
  "sideEffects": false,
  "scripts": {
    "build": "tsc -p tsconfig.json"
  },
  "dependencies": {
    "@rulegate/adapter-kit": "workspace:*"
  }
}
`;
}

function tsconfig(): string {
  return `{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": "src",
    "outDir": "dist"
  },
  "include": ["src/**/*"],
  "exclude": ["src/**/*.test.ts", "dist"]
}
`;
}

function adapterSource(n: ToolNames): string {
  return `import {
  ADAPTER_API_VERSION,
  detected,
  finalizeArtifact,
  importConcatenated,
  isCanonicalSource,
  renderConcatenated,
  selects,
  sortRules,
  withHtmlMarker,
  type Adapter,
  type AdapterContext,
  type Artifact,
  type Canonical,
  type DetectResult,
} from '@rulegate/adapter-kit';
import { docs } from './docs.js';

/**
 * Scaffolded by \`rulegate adapter new ${n.id}\`.
 *
 * What is here is a working adapter of the commonest shape: one Markdown file, every
 * rule joined under a \`##\` heading. It passes \`pnpm test\` as generated, which means the
 * next failure you see is a real one.
 *
 * Three things to change, in this order:
 *
 *   1. \`fixtures/${n.id}/expected/${n.artifact}\` — hand-write the bytes ${n.title} actually
 *      reads, from its documentation. The golden shipped with the scaffold was generated
 *      by this file, so it proves only that the adapter agrees with itself.
 *   2. \`src/docs.ts\` — every placeholder in it is marked TODO. That file is the reason
 *      \`rulegate doctor\` can say which file wins; a wrong entry there is a wrong answer.
 *   3. this file — the artifact path, the heading level, and the detection paths.
 */
export const ${n.constant} = '${n.artifact}';

/** Anything that means "this repository uses ${n.title}". \`doctor\` reports it as evidence. */
const DETECTION_PATHS = ['${n.dotDir}', ${n.constant}] as const;

async function detect(ctx: AdapterContext): Promise<DetectResult> {
  const evidence: string[] = [];
  for (const path of DETECTION_PATHS) {
    if (await ctx.fs.exists(path)) evidence.push(path);
  }
  return detected(evidence);
}

/** Native config -> canonical: what \`rulegate init\` runs on a repo that never adopted us. */
async function read(ctx: AdapterContext): Promise<Partial<Canonical>> {
  // Never import a file that is already the canonical source: the parser has read it, and
  // importing it again duplicates every rule in it.
  if (isCanonicalSource(ctx.canonical.manifest, ${n.constant})) return {};

  const contents = await ctx.fs.tryReadFile(${n.constant});
  if (contents === undefined) return {};

  return {
    rules: importConcatenated({
      file: ${n.constant},
      contents,
      headingLevel: 2,
      idFallback: '${n.id}',
    }),
  };
}

/** Canonical -> native config. Pure: return artifacts, never touch the disk. */
async function write(ctx: AdapterContext): Promise<readonly Artifact[]> {
  const { canonical } = ctx;

  if (isCanonicalSource(canonical.manifest, ${n.constant})) return [];

  const rules = sortRules(canonical.rules.filter((r) => selects(r.frontmatter.tools, '${n.id}')));
  if (rules.length === 0) return [];

  const body = renderConcatenated(rules, { headingLevel: 2, showGlobs: true });

  return Promise.resolve([
    finalizeArtifact({
      path: ${n.constant},
      contents: withHtmlMarker(body, canonical.manifest.options.marker),
      adapter: '${n.id}',
      kind: 'rules',
      provenance: { ruleIds: rules.map((r) => r.id) },
    }),
  ]);
}

export const ${n.binding}: Adapter = {
  name: '${n.id}',
  apiVersion: ADAPTER_API_VERSION,
  detect,
  read,
  write,
  docs,
};

export default ${n.binding};
export { docs };
`;
}

function adapterDocs(n: ToolNames): string {
  return `import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

// TODO: the page you actually read. \`doctor\` prints it, and a reviewer checks it.
const ${n.constant.replace(/_MD$/, '')}_DOCS: SourceLink = {
  url: 'https://example.com/${n.id}/docs',
  title: 'TODO: ${n.title} — where its instruction files are documented',
  retrieved: '1970-01-01',
};

/**
 * What ${n.title} actually loads, and in what order.
 *
 * This is the part of an adapter nobody else has written down, and it is what lets
 * \`rulegate doctor\` answer "which file wins". Treat it as versioned data, not comments:
 * every claim carries a source URL and the version it was verified against.
 *
 * The placeholders below are deliberately wrong rather than plausible — \`1970-01-01\` and
 * \`example.com\` cannot be mistaken for a verified claim. \`pnpm test\` checks the *shape*
 * of this file; only you can check whether it is true.
 */
export const docs: AdapterDocs = {
  toolName: '${n.title}',
  homepage: 'https://example.com/${n.id}',
  verifiedAgainst: { version: 'TODO: the version you checked against', date: '1970-01-01' },
  // 'override': the nearest file replaces the others, so files[0] is the only one that
  // matters. 'additive': every file found is sent at once, and the order ranks
  // specificity rather than authority. Getting this wrong makes doctor lie.
  resolution: 'override',
  files: [
    {
      pattern: '${n.artifact}',
      scope: 'project',
      role: 'instructions',
      managed: true,
      description: 'TODO: the file this adapter generates, and when ${n.title} reads it.',
      source: ${n.constant.replace(/_MD$/, '')}_DOCS,
    },
    // TODO: add the files ${n.title} reads that Rulegate does *not* write — a user-level
    // \`~/...\` file (scope: 'global'), nested per-directory files (scope: 'nested', with
    // \`nesting\`), settings files. \`doctor\` reports them, and an absent entry is a file the
    // user cannot see.
  ],
  // TODO: the documented cap, or a note saying none is published. "No limit" and "nobody
  // checked" must not look the same.
  limits: { note: 'TODO: the documented size cap, or a sentence saying none is published.' },
};
`;
}

function detectTest(n: ToolNames): string {
  return `import { describe, expect, it } from 'vitest';
import { contextFor, detectFixture } from '@rulegate/adapter-kit/testing';
import { ${n.binding} } from '../src/index.js';

describe('${n.id} detect()', () => {
  it('finds ${n.title} and says what gave it away', async () => {
    const ctx = await contextFor(detectFixture('${n.id}', 'positive'), ${n.binding});
    const result = await ${n.binding}.detect(ctx);

    expect(result.detected).toBe(true);
    // Evidence is sorted, so this is the order \`doctor\` prints.
    expect(result.evidence).toEqual(['${n.artifact}', '${n.dotDir}'].sort());
  });

  it('reports absence on a repo that does not use it', async () => {
    const ctx = await contextFor(detectFixture('${n.id}', 'negative'), ${n.binding});
    const result = await ${n.binding}.detect(ctx);

    expect(result.detected).toBe(false);
    expect(result.evidence).toEqual([]);
  });
});
`;
}

function writeTest(n: ToolNames): string {
  return `import { describe, expect, it } from 'vitest';
import type { Canonical } from '@rulegate/adapter-kit';
import {
  contextFor,
  expectFixtureMatch,
  expectIdempotent,
  renderFixture,
} from '@rulegate/adapter-kit/testing';
import { ${n.binding}, ${n.constant} } from '../src/index.js';

describe('${n.id} write()', () => {
  it('matches the golden fixture byte for byte', async () => {
    await expectFixtureMatch('${n.id}', ${n.binding});
  });

  it('is idempotent across repeated renders', async () => {
    // Determinism is a contract (NFR4): \`check\` compares bytes, so output that varies
    // between runs is drift the user cannot fix.
    await expectIdempotent('${n.id}', ${n.binding});
  });

  it('excludes rules that target other tools', async () => {
    const actual = await renderFixture('${n.id}', ${n.binding});
    expect(actual.get(${n.constant})).not.toContain('This rule must not reach ${n.id}');
  });

  it('records which rules produced the file', async () => {
    const ctx = await contextFor('${n.id}/input', ${n.binding});
    const [artifact] = await ${n.binding}.write(ctx);

    expect(artifact?.provenance?.ruleIds).toEqual(['10-style', '20-testing']);
  });

  it('emits no file when no rule targets this tool', async () => {
    const ctx = await contextFor('${n.id}/input', ${n.binding});
    const canonical: Canonical = { ...ctx.canonical, rules: [] };
    expect(await ${n.binding}.write({ ...ctx, canonical })).toEqual([]);
  });
});
`;
}

function readTest(n: ToolNames): string {
  return `import { describe, it } from 'vitest';
import { expectContentCovered, expectImportMatch } from '@rulegate/adapter-kit/testing';
import { ${n.binding} } from '../src/index.js';

describe('${n.id} read()', () => {
  it('imports the fixture repo into the expected canonical rules', async () => {
    await expectImportMatch('${n.id}', ${n.binding});
  });

  it('loses no user content', async () => {
    // The assertion that matters on a first run: \`init\` must not drop a line of
    // somebody's existing config on the way into .rulegate/.
    await expectContentCovered('${n.id}', ${n.binding}, ['${n.artifact}']);
  });
});
`;
}
