import type { AdapterDocs, SourceLink } from '@rulegate/adapter-kit';

const RULES_DOCS: SourceLink = {
  url: 'https://opencode.ai/docs/rules/',
  title: 'OpenCode — Rules',
  retrieved: '2026-09-26',
};

const CONFIG_DOCS: SourceLink = {
  url: 'https://opencode.ai/docs/config/',
  title: 'OpenCode — Config',
  retrieved: '2026-09-26',
};

/**
 * The source, cited because the docs page does not say it: layers merge, and
 * `instructions` alone is concatenated rather than replaced. Everything this adapter
 * writes depends on that one line.
 */
const CONFIG_SOURCE: SourceLink = {
  url: 'https://github.com/sst/opencode/blob/dev/packages/opencode/src/config/config.ts',
  title: 'OpenCode source — config.ts (mergeConfigConcatArrays)',
  retrieved: '2026-09-26',
};

const INSTRUCTION_SOURCE: SourceLink = {
  url: 'https://github.com/sst/opencode/blob/dev/packages/opencode/src/session/instruction.ts',
  title: 'OpenCode source — instruction.ts (systemPaths)',
  retrieved: '2026-09-26',
};

/**
 * What OpenCode actually loads, and in what order.
 *
 * Two mechanisms with two resolutions, and the kit takes one per tool. `AGENTS.md` and
 * `CLAUDE.md` are **first-match** — the first one found walking up wins and the other is
 * never read — while every `instructions` entry is sent in addition. `'additive'` is
 * declared because the files Rulegate writes are on the additive side; the cost of the
 * choice is stated in a note rather than hidden.
 */
export const docs: AdapterDocs = {
  toolName: 'OpenCode',
  homepage: 'https://opencode.ai',
  verifiedAgainst: { version: 'opencode 1.18.32 (source, dev branch)', date: '2026-09-26' },
  resolution: 'additive',
  files: [
    {
      pattern: '.opencode/opencode.json',
      scope: 'project',
      role: 'settings',
      managed: true,
      description:
        'A config layer of its own, merged over the root opencode.json, holding only $schema and an instructions list naming the generated rule files. Rulegate owns this file whole and never touches the root config; one it did not write is refused rather than overwritten.',
      source: CONFIG_SOURCE,
    },
    {
      pattern: '.opencode/opencode.jsonc',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        'The JSONC spelling of the .opencode/ config layer. Rulegate writes the .json spelling only; a .jsonc here is imported like the root config and never written.',
      source: CONFIG_DOCS,
    },
    {
      pattern: '.opencode/rules/*.md',
      scope: 'project',
      role: 'instructions',
      managed: true,
      description:
        'One Markdown file per rule, loaded because .opencode/opencode.json lists it. A file here that is not listed is not loaded. This is what Rulegate generates.',
      source: RULES_DOCS,
    },
    {
      pattern: 'opencode.json',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        "The user's project config. Its instructions entries are imported (local files only) and it is never written.",
      source: CONFIG_DOCS,
    },
    {
      pattern: 'opencode.jsonc',
      scope: 'project',
      role: 'settings',
      managed: false,
      description:
        'The JSONC spelling of the project config. Imported like opencode.json, never written.',
      source: CONFIG_DOCS,
    },
    {
      pattern: 'AGENTS.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'Every AGENTS.md from the working directory up to the worktree root; when any is found, CLAUDE.md is not read at all. Generated by the codex adapter, not by this one — so enabling opencode and codex together sends OpenCode the same rules twice.',
      source: RULES_DOCS,
    },
    {
      pattern: 'CLAUDE.md',
      scope: 'project',
      role: 'instructions',
      managed: false,
      nesting: 'all-merged',
      description:
        'The Claude Code fallback, read (at every level up to the worktree root) only when no AGENTS.md is found. Generated by the claude-code adapter, not by this one.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.config/opencode/AGENTS.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'User-level rules. Outside the repository, so Rulegate reports it and never writes it.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.claude/CLAUDE.md',
      scope: 'global',
      role: 'instructions',
      managed: false,
      description:
        'The Claude Code user file, read only when ~/.config/opencode/AGENTS.md is absent, and unless OPENCODE_DISABLE_CLAUDE_CODE is set.',
      source: RULES_DOCS,
    },
    {
      pattern: '~/.config/opencode/opencode.json',
      scope: 'global',
      role: 'settings',
      managed: false,
      description:
        'The global config layer. Its instructions are concatenated with the project layers. Reported, never written.',
      source: CONFIG_DOCS,
    },
  ],
  limits: {
    note: 'OpenCode documents no size cap on instruction files. The only documented limit is a 5-second timeout on fetching a remote instruction URL.',
  },
  notes: [
    {
      level: 'warn',
      message:
        'Rulegate owns .opencode/opencode.json entirely and writes only $schema and instructions into it. Put every other setting in the root opencode.json: OpenCode merges the two, and a setting added to the generated file is reported by check as a hand-edit and overwritten only with --force.',
      source: CONFIG_SOURCE,
    },
    {
      level: 'info',
      message:
        "instructions arrays are concatenated (and de-duplicated) across config layers rather than replaced, so the list Rulegate writes adds to the root config's list instead of hiding it. The config page says only that layers merge; the concatenation is in the source (mergeConfigConcatArrays).",
      source: CONFIG_SOURCE,
    },
    {
      level: 'info',
      message:
        'The generated config carries no "//" marker key: OpenCode\'s schema rejects unknown keys, so the marker every other generated JSON file carries would make this one invalid. Ownership is recorded in .rulegate/state.json as it is for every artifact.',
      source: CONFIG_SOURCE,
    },
    {
      level: 'warn',
      message:
        'Resolution is declared additive, but AGENTS.md and CLAUDE.md are first-match: when both exist OpenCode reads only AGENTS.md. In a repository with both, doctor bills CLAUDE.md to OpenCode although OpenCode never opens it, so its token estimate for OpenCode runs high.',
      source: RULES_DOCS,
    },
    {
      level: 'info',
      message:
        'Relative instructions entries are resolved by searching upward from the working directory to the worktree root, not relative to the config file. Import treats them as repository-relative, and skips remote URLs, home-directory and absolute paths, anything under .agent-os/, .ruler/, .rulesync/ or .rulegate/, and any file another adapter imports (AGENTS.md, .cursor/rules/*.mdc, .github/copilot-instructions.md and the like — matched by the patterns that adapter reads, so .claude/docs/ is still imported), each with a warning. An unlisted file in .opencode/rules/ is not imported, with a warning, because OpenCode does not load it and `init --yes` would replace it if an imported rule takes its name.',
      source: INSTRUCTION_SOURCE,
    },
  ],
};
